"""An async Jupyter kernel client over HTTP and websockets

Docs: https://AnswerDotAI.github.io/jupyasyncclient/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['log', 'dumps', 'loads', 'serialize_binary_message', 'deserialize_binary_message', 'KernelApi',
           'JupyAsyncKernelClient']

# %% ../nbs/00_core.ipynb #a0271b3e
import asyncio, json, logging, os, time, uuid, httpx, websockets
from contextlib import suppress
from queue import Empty
from urllib.parse import urlencode, urlsplit, urlunsplit
from jupyter_client.client import validate_string_dict
from fastcore.basics import xdumps, revive_dates
from fastcore.nbio import pack_frames, unpack_frames
from jupyter_client.session import Session
from fastcore.basics import patch
from fastcore.meta import use_kwargs_dict

# %% ../nbs/00_core.ipynb #1c375452
log = logging.getLogger('jupyasyncclient')

# %% ../nbs/00_core.ipynb #3e850d28
def dumps(msg): return xdumps(msg)

def loads(s: str):
    msg = json.loads(s)
    if isinstance(msg, dict):
        for k in ("header", "parent_header"):
            if isinstance(msg.get(k), dict): msg[k] = revive_dates(msg[k])
    return msg


# %% ../nbs/00_core.ipynb #26fed730
def serialize_binary_message(msg):
    msg = msg.copy()
    buffers = msg.pop("buffers")
    return pack_frames(dumps(msg).encode("utf8"), buffers)

def deserialize_binary_message(bmsg: bytes):
    body, bufs = unpack_frames(bmsg)
    msg = loads(body.decode("utf8"))
    msg["buffers"] = [memoryview(b) for b in bufs]
    return msg


# %% ../nbs/00_core.ipynb #23408417
def _join_url(base, path, ws=False, params=None):
    u = urlsplit(base)
    scheme = {"http": "ws", "https": "wss"}.get(u.scheme, u.scheme) if ws else u.scheme
    base_path = u.path.rstrip("/")
    full_path = f"{base_path}/{path.lstrip('/')}" if path else base_path
    query = urlencode({k: v for k, v in (params or {}).items() if v is not None})
    return urlunsplit((scheme, u.netloc, full_path, query, ""))

# %% ../nbs/00_core.ipynb #b5f06ba9
class KernelApi:
    "Shared HTTP plumbing for the Jupyter kernels API."
    def __init__(self, base_url, token=None, headers=None, timeout=30, http_client=None):
        self.base_url,self.token,self._timeout = base_url.rstrip('/'),token or '',timeout
        self._headers = {**(headers or {})}
        if self.token and 'Authorization' not in self._headers: self._headers['Authorization'] = f'token {self.token}'
        self._http,self._own_http = http_client,http_client is None

    def _ensure_http(self):
        if self._http and not self._http.is_closed: return self._http
        self._http,self._own_http = httpx.AsyncClient(headers=self._headers),True
        return self._http

    async def _request(self, method, path, **kwargs):
        r = await self._ensure_http().request(method, _join_url(self.base_url, path), **kwargs)
        r.raise_for_status()
        if r.status_code==204: return True
        ct = (r.headers.get('content-type') or '').split(';')[0]
        return r.json() if ct=='application/json' else r.text

    def _kpath(self, kernel_id='', suffix=''): return f"/api/kernels/{kernel_id}{suffix}" if kernel_id else '/api/kernels'

    async def kernel_request(self, method, kernel_id='', suffix='', **kwargs):
        return await self._request(method, self._kpath(kernel_id, suffix), **kwargs)

    async def aclose_http(self):
        if self._http and self._own_http and not self._http.is_closed: await self._http.aclose()

# %% ../nbs/00_core.ipynb #7efec2a1
class JupyAsyncKernelClient(KernelApi):
    "AsyncKernelClient-ish API over the kernels HTTP API plus its websocket channels."
    allow_stdin = True
    def __init__(self, base_url, kernel_id=None, token=None, session_id=None, username=None, headers=None, timeout=30, http_client=None,
        reconnect=True, reconnect_ceiling=300.0):
        super().__init__(base_url, token=token, headers=headers, timeout=timeout, http_client=http_client)
        self.kernel_id = kernel_id
        self.session_id = session_id or uuid.uuid4().hex
        self.session = Session(session=self.session_id, username=username or os.environ.get("USER") or "")
        self._ws,self._start_task,self._send_task,self._recv_task,self._close_task = [None]*5
        self.reconnect,self.reconnect_ceiling,self._unsent,self._closing = reconnect,reconnect_ceiling,None,False
        self._send_q = asyncio.Queue()
        self._queues = {k: asyncio.Queue() for k in ("shell", "iopub", "stdin", "control")}
        self._reply_waiters = {k: {} for k in ("shell", "control")}
        self._stale_replies = {k: set() for k in ("shell", "control")}
        self._last_stdin_req = None

    def _kpath(self, kernel_id='', suffix=''): return super()._kpath(kernel_id or self.kernel_id, suffix)

    async def kernel_request(self, method, suffix="", **kwargs):
        if not self.kernel_id: return None
        return await super().kernel_request(method, self.kernel_id, suffix, **kwargs)

# %% ../nbs/00_core.ipynb #1263d477
@patch
async def start_kernel(self:JupyAsyncKernelClient, kernel_name="python3", **kwargs):
    model = await self._request("POST", self._kpath(''), json={"name": kernel_name, **kwargs})
    self.kernel_id = model["id"]
    return model

# %% ../nbs/00_core.ipynb #bc577f39
@patch
async def shutdown_kernel(self: JupyAsyncKernelClient): return await self.kernel_request("DELETE")
@patch
async def interrupt_kernel(self: JupyAsyncKernelClient): return await self.kernel_request("POST", "/interrupt")
@patch
async def restart_kernel(self: JupyAsyncKernelClient): return await self.kernel_request("POST", "/restart")

@patch
async def is_alive(self: JupyAsyncKernelClient):
    try: return bool(await self.kernel_request("GET"))
    except Exception: return False


# %% ../nbs/00_core.ipynb #38c3312b
@patch
def _fail_pending(self: JupyAsyncKernelClient, exc, channel="shell", skip=None):
    "Fail all pending reply waiters on `channel` (except `skip`), e.g. when an error aborts the kernel's queue."
    for mid, (fut, _) in list(self._reply_waiters[channel].items()):
        if mid != skip and not fut.done(): fut.set_exception(exc)

@patch
def _route_reply_or_queue(self: JupyAsyncKernelClient, msg):
    channel = msg.pop("channel", None) or "shell"
    msg.setdefault("msg_id", msg.get("header", {}).get("msg_id"))
    msg.setdefault("msg_type", msg.get("header", {}).get("msg_type"))
    msg.setdefault("buffers", [])
    if channel == "stdin" and msg["msg_type"] == "input_request": self._last_stdin_req = msg.get("header")
    parent_msg_id = msg.get("parent_header", {}).get("msg_id")
    if channel in self._reply_waiters and parent_msg_id:
        pend = self._reply_waiters[channel].pop(parent_msg_id, None)
        if pend:
            fut, fail_pending = pend
            if not fut.done(): fut.set_result(msg)
            cts = msg.get("content", {})
            if fail_pending and cts.get("status") in ("error", "aborted"):
                exc = RuntimeError(f"Kernel error aborted: {cts.get('ename')}: {cts.get('evalue')}")
                self._fail_pending(exc, channel, skip=parent_msg_id)
            return
        if parent_msg_id in self._stale_replies[channel]:
            self._stale_replies[channel].discard(parent_msg_id)
            return
    q = self._queues.get(channel)
    if q: q.put_nowait(msg)

# %% ../nbs/00_core.ipynb #0e8ce8d5
@patch
async def _ensure_started(self: JupyAsyncKernelClient):
    if not self._start_task: self.start_channels()
    if self._start_task: await self._start_task

@patch
def _queue_msg(self: JupyAsyncKernelClient, msg, channel: str):
    msg = dict(msg)
    msg["channel"] = channel
    bufs = msg.get("buffers")
    if bufs:
        msg["buffers"] = [bytes(b) for b in bufs]
        payload = serialize_binary_message(msg)
    else:
        msg.pop("buffers", None)
        payload = dumps(msg)
    self._send_q.put_nowait(payload)
    return msg["header"]["msg_id"]

@patch
async def _get_msg(self: JupyAsyncKernelClient, channel, timeout=None):
    await self._ensure_started()
    q = self._queues[channel]
    try:
        async with asyncio.timeout(timeout): return await q.get()
    except asyncio.TimeoutError as e: raise Empty from e

# %% ../nbs/00_core.ipynb #7bf0ff55
@patch
async def _send_loop(self: JupyAsyncKernelClient):
    assert self._ws is not None
    while True:
        payload = self._unsent if self._unsent is not None else await self._send_q.get()
        if payload is None: return
        self._unsent = payload
        try: await self._ws.send(payload)
        except Exception as e:
            log.warning("websocket send failed: %s", e)
            return  # the payload stays in `_unsent`: a reconnected send loop retries it first
        self._unsent = None

@patch
async def _recv_loop(self: JupyAsyncKernelClient):
    assert self._ws is not None
    with suppress(websockets.ConnectionClosed):
        async for data in self._ws:
            if isinstance(data, str): msg = loads(data)
            elif isinstance(data, bytes): msg = deserialize_binary_message(data)
            else: continue
            self._route_reply_or_queue(msg)
    if self.reconnect and not self._closing: self._start_task = asyncio.create_task(self._reconnect())

# %% ../nbs/00_core.ipynb #3cd67196
@patch
async def _start_ws(self: JupyAsyncKernelClient):
    if self._ws and self._ws.close_code is None: return
    for t in (self._send_task, self._recv_task):
        if t and not t.done(): t.cancel()  # a stale send loop must not steal payloads from the new one
    params = {"session_id": self.session_id}
    if self.token: params["token"] = self.token
    ws_url = _join_url(self.base_url, self._kpath(suffix="/channels"), ws=True, params=params)
    self._ws = await websockets.connect(ws_url, additional_headers=self._headers, ping_interval=30)
    self._send_task = asyncio.create_task(self._send_loop())
    self._recv_task = asyncio.create_task(self._recv_loop())

# %% ../nbs/00_core.ipynb #0c4eb750
@patch
async def _send_and_await_reply(self: JupyAsyncKernelClient, msg, msg_id, timeout=None, channel="shell", fail_pending=False):
    fut = asyncio.get_running_loop().create_future()
    self._reply_waiters[channel][msg_id] = (fut, fail_pending)
    self._queue_msg(msg, channel)
    try:
        async with asyncio.timeout(timeout): return await fut
    finally:
        popped = self._reply_waiters[channel].pop(msg_id, None)
        if popped and popped[0] is fut and (not fut.done() or fut.cancelled()): self._stale_replies[channel].add(msg_id)

# %% ../nbs/00_core.ipynb #6606950e
@patch
def _exec_req(self: JupyAsyncKernelClient, name, content=None, channel="shell", metadata=None, reply=False, timeout=None, subshell_id=None,
    parent=None, fail_pending=False):
    msg = self.session.msg(name, content, metadata=metadata, parent=parent)
    if subshell_id: msg["header"]["subshell_id"] = subshell_id
    msg_id = msg["header"]["msg_id"]
    if not reply: return self._queue_msg(msg, channel)
    return self._send_and_await_reply(msg, msg_id, timeout=timeout, channel=channel, fail_pending=fail_pending)

def _gen_request(self, name):
    "Generated `*_request`/`*_reply` senders; other names raise, so typos fail instead of sending bogus messages. Assigned onto the class below (a module-level `__getattr__` would become a PEP 562 hook)."
    if name.startswith("_") or not name.endswith(("_request", "_reply")): raise AttributeError(name)
    def _f(reply=False, timeout=None, channel="shell", metadata=None, subshell_id=None, parent=None, fail_pending=False, **kwargs):
        return self._exec_req(name, content=kwargs or None, reply=reply, timeout=timeout, channel=channel, metadata=metadata,
            subshell_id=subshell_id, parent=parent, fail_pending=fail_pending)
    return _f

JupyAsyncKernelClient.__getattr__ = _gen_request

# %% ../nbs/00_core.ipynb #f5d47bbe
@patch
def start_channels(self: JupyAsyncKernelClient, shell=True, iopub=True, stdin=True, control=True):
    if not (shell or iopub or stdin or control): return
    if self._start_task and not self._start_task.done(): return
    self._start_task = asyncio.create_task(self._start_ws())
    return self

# %% ../nbs/00_core.ipynb #08793aa7
@patch(as_prop=True)
def channels_running(self: JupyAsyncKernelClient): return bool(self._ws and self._ws.close_code is None)

# %% ../nbs/00_core.ipynb #22d28a55
@patch
async def get_shell_msg(self: JupyAsyncKernelClient, timeout=None): return await self._get_msg("shell", timeout)
@patch
async def get_iopub_msg(self: JupyAsyncKernelClient, timeout=None): return await self._get_msg("iopub", timeout)
@patch
async def get_stdin_msg(self: JupyAsyncKernelClient, timeout=None): return await self._get_msg("stdin", timeout)
@patch
async def get_control_msg(self: JupyAsyncKernelClient, timeout=None): return await self._get_msg("control", timeout)

# %% ../nbs/00_core.ipynb #f3407997
@patch
async def wait_for_ready(self: JupyAsyncKernelClient, timeout=None):
    await self._ensure_started()
    await self.kernel_info_request(reply=True, timeout=timeout)
    while True:
        try: await self.get_iopub_msg(timeout=0.05)
        except Empty: return

# %% ../nbs/00_core.ipynb #65a13919
_replkw = dict(reply=False, timeout=None)
_subskw = dict(**_replkw, subshell_id=None)

# %% ../nbs/00_core.ipynb #7daa3f7a
@patch
@use_kwargs_dict(**_subskw)
def execute(self: JupyAsyncKernelClient, code, silent=False, store_history=True, user_expressions=None, allow_stdin=None, stop_on_error=True,
    fail_pending=False, **kwargs):
    user_expressions = {} if user_expressions is None else user_expressions
    allow_stdin = self.allow_stdin if allow_stdin is None else allow_stdin
    if not isinstance(code, str): raise ValueError(f"code {code!r} must be a string")
    validate_string_dict(user_expressions)
    return self.execute_request(code=code, silent=silent, store_history=store_history, user_expressions=user_expressions,
        allow_stdin=allow_stdin, stop_on_error=stop_on_error, fail_pending=fail_pending, **kwargs)

# %% ../nbs/00_core.ipynb #d75ce9da
@patch
@use_kwargs_dict(**_replkw)
def create_subshell(self: JupyAsyncKernelClient, **kwargs): return self.create_subshell_request(channel="control", **kwargs)

@patch
@use_kwargs_dict(**_replkw)
def list_subshell(self: JupyAsyncKernelClient, **kwargs): return self.list_subshell_request(channel="control", **kwargs)

@patch
@use_kwargs_dict(**_replkw)
def delete_subshell_request(self: JupyAsyncKernelClient, subshell_id: str, metadata=None, **kwargs):
    return self._exec_req("delete_subshell_request", content={"subshell_id": subshell_id}, channel="control", metadata=metadata, **kwargs)

@patch
@use_kwargs_dict(**_replkw)
def delete_subshell(self: JupyAsyncKernelClient, subshell_id: str, **kwargs): return self.delete_subshell_request(subshell_id=subshell_id, **kwargs)

# %% ../nbs/00_core.ipynb #057d4d1a
@patch
def input(self: JupyAsyncKernelClient, string: str):
    "Answer an `input_request`, parented to it so kernels and gateways can match reply to prompt."
    parent, self._last_stdin_req = self._last_stdin_req, None
    self.input_reply(value=string, channel="stdin", parent=parent)

# %% ../nbs/00_core.ipynb #b961668b
@patch
@use_kwargs_dict(**_subskw)
def complete(self: JupyAsyncKernelClient, code, cursor_pos=None, **kwargs):
    cursor_pos = len(code) if cursor_pos is None else cursor_pos
    return self.complete_request(code=code, cursor_pos=cursor_pos, **kwargs)

# %% ../nbs/00_core.ipynb #2899c6b1
@patch
@use_kwargs_dict(**_subskw)
def inspect(self: JupyAsyncKernelClient, code, cursor_pos=None, detail_level=0, **kwargs):
    cursor_pos = len(code) if cursor_pos is None else cursor_pos
    return self.inspect_request(code=code, cursor_pos=cursor_pos, detail_level=detail_level, **kwargs)

# %% ../nbs/00_core.ipynb #9775d16f
@patch
@use_kwargs_dict(**_subskw, keep=True)
def history(self: JupyAsyncKernelClient, raw=True, output=False, hist_access_type="range", **kwargs):
    if hist_access_type=="range":
        kwargs.setdefault("session", 0)
        kwargs.setdefault("start", 0)
    return self.history_request(raw=raw, output=output, hist_access_type=hist_access_type, **kwargs)

# %% ../nbs/00_core.ipynb #52045159
@patch
@use_kwargs_dict(**_subskw)
def comm_info(self: JupyAsyncKernelClient, target_name=None, **kwargs): return self.comm_info_request(target_name=target_name, **kwargs)

@patch
@use_kwargs_dict(**_subskw)
def kernel_info(self: JupyAsyncKernelClient, **kwargs): return self.kernel_info_request(**kwargs)

@patch
@use_kwargs_dict(**_subskw)
def is_complete(self: JupyAsyncKernelClient, code, **kwargs): return self.is_complete_request(code=code, **kwargs)

# %% ../nbs/00_core.ipynb #97540d7e
@patch
async def _reconnect(self: JupyAsyncKernelClient):
    "Redial with the same session id, with backoff; on a dead kernel or an expired ceiling, fail the pending futures."
    deadline, delay = time.monotonic() + self.reconnect_ceiling, 0.1
    while not self._closing:
        try:
            await self._start_ws()
            log.info("websocket reconnected")
            return
        except Exception as e:
            exc = None
            try: await self.kernel_request('GET')
            except httpx.HTTPStatusError as he: exc = RuntimeError(f'kernel {self.kernel_id} is gone: {he}')
            except Exception: pass  # the server is unreachable too: keep trying until the ceiling
            if exc is None and time.monotonic() > deadline: exc = ConnectionError(f'gave up reconnecting after {self.reconnect_ceiling}s: {e}')
            if exc:
                for c in ('shell','control'): self._fail_pending(exc, c)
                raise exc
            await asyncio.sleep(delay)
            delay = min(delay*2, 5.0)

# %% ../nbs/00_core.ipynb #893a89e0
@patch
@use_kwargs_dict(**_replkw)
def shutdown(self: JupyAsyncKernelClient, restart=False, **kwargs):
    return self.shutdown_request(restart=restart, channel="control", **kwargs)

# %% ../nbs/00_core.ipynb #8dccd345
@patch
async def aclose(self: JupyAsyncKernelClient):
    self._closing = True
    for t in (self._start_task, self._send_task, self._recv_task):
        if t and not t.done(): t.cancel()
    if self._ws and self._ws.close_code is None: await self._ws.close()
    for t in (self._start_task, self._send_task, self._recv_task):
        if t:
            with suppress(asyncio.CancelledError, Exception): await t
    for d in self._reply_waiters.values():
        for fut, _ in d.values():
            if not fut.done(): fut.cancel()
        d.clear()
    for s in self._stale_replies.values(): s.clear()
    self._ws = None
    await self.aclose_http()

@patch
def stop_channels(self: JupyAsyncKernelClient):
    if self._close_task and not self._close_task.done(): return
    self._close_task = asyncio.create_task(self.aclose())
