"""An async Jupyter kernel client over HTTP and websockets

Docs: https://AnswerDotAI.github.io/jupyasyncclient/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['log', 'rg_spec', 'build_spec', 'KernelApi', 'JupyAsyncKernelClient']

# %% ../nbs/00_core.ipynb #a0271b3e
import asyncio, functools, inspect, json, logging, os, ssl, time, uuid, websockets
from fasttransport.core import AsyncTransport
from fastspec.oapi import OpenAPIClient, SpecParser
from fasttransport.errors import APIError
from contextlib import suppress
from urllib.parse import urlencode, urlsplit, urlunsplit
from jupywire.session import Session, validate_string_dict, dumps, loads, serialize_binary_message, deserialize_binary_message
from jupywire.ops import EvalOps
from jupywire.route import RouterOps, DeadKernelError
from fastcore.basics import patch
from fastcore.xtras import dict2obj
from fastcore.net import urlread


# %% ../nbs/00_core.ipynb #1c375452
log = logging.getLogger('jupyasyncclient')

# %% ../nbs/00_core.ipynb #23408417
def _join_url(base, path, ws=False, params=None):
    u = urlsplit(base)
    scheme = {"http": "ws", "https": "wss"}.get(u.scheme, u.scheme) if ws else u.scheme
    base_path = u.path.rstrip("/")
    full_path = f"{base_path}/{path.lstrip('/')}" if path else base_path
    query = urlencode({k: v for k, v in (params or {}).items() if v is not None})
    return urlunsplit((scheme, u.netloc, full_path, query, ""))

# %% ../nbs/00_core.ipynb #b5f06ba9
@functools.cache
def rg_spec():
    "The bundled rustygate spec, loaded once per process from its compact `rg_spec` module."
    from jupyasyncclient.rg_spec import spec
    return SpecParser.from_dict(spec)

def build_spec(nm='jupyasyncclient/rg_spec.py', url='http://localhost:8787'):
    "Regenerate the compact spec module `rg_spec.py` from a running rustygate's `/openapi.json`."
    SpecParser.from_openapi(dict2obj(json.loads(urlread(f'{url}/openapi.json')))).save(nm)

class KernelApi:
    "Shared HTTP plumbing for the Jupyter kernels API: one transport, and the spec-generated ops on `api`."
    def __init__(self, base_url, token=None, headers=None, timeout=30, http_client=None, verify=True):
        self.base_url,self.token,self._timeout,self.verify = base_url.rstrip('/'),token or '',timeout,verify
        self._headers = {**(headers or {})}
        if self.token and 'Authorization' not in self._headers: self._headers['Authorization'] = f'token {self.token}'
        self.transport = AsyncTransport(timeout=timeout, client=http_client, base_headers=self._headers, verify=verify)
        self.api = OpenAPIClient(rg_spec(), transport=self.transport, base_url=self.base_url)

    def _ws_ssl(self, url):
        "An unverified ssl context when `verify=False` and `url` is wss, else None for the library default."
        if self.verify or not url.startswith('wss'): return None
        ctx = ssl.create_default_context()
        ctx.check_hostname,ctx.verify_mode = False,ssl.CERT_NONE
        return ctx

    def _kpath(self, kernel_id='', suffix=''): return f"/api/kernels/{kernel_id}{suffix}" if kernel_id else '/api/kernels'

# %% ../nbs/00_core.ipynb #7efec2a1
class JupyAsyncKernelClient(RouterOps, EvalOps, KernelApi):
    "AsyncKernelClient-ish API over the kernels HTTP API plus its websocket channels."
    allow_stdin = True
    def __init__(self, base_url, kernel_id=None, token=None, session_id=None, username=None, headers=None, timeout=30, http_client=None,
        reconnect=True, reconnect_ceiling=300.0, verify=True, max_size=256*2**20):
        super().__init__(base_url, token=token, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.kernel_id = kernel_id
        self.owned = False    # True only when `connect` created the kernel; honored by `__aexit__`
        self.session_id = session_id or uuid.uuid4().hex
        self.session = Session(session=self.session_id, username=username or os.environ.get("USER") or "")
        self._ws,self._start_task,self._send_task,self._recv_task,self._close_task = [None]*5
        self.reconnect,self.reconnect_ceiling,self._unsent,self._closing = reconnect,reconnect_ceiling,None,False
        self.max_size = max_size
        self._send_q = asyncio.Queue()
        self._init_router()

    def _kpath(self, kernel_id='', suffix=''): return super()._kpath(kernel_id or self.kernel_id, suffix)

# %% ../nbs/00_core.ipynb #8dccd345
@patch
async def aclose(self: JupyAsyncKernelClient):
    self._closing = True
    if self._send_task and not self._send_task.done():   # the None sentinel ends `_send_loop` once the queue has drained
        self._send_q.put_nowait(None)
        with suppress(Exception):
            async with asyncio.timeout(2): await self._send_task
    for t in (self._start_task, self._send_task, self._recv_task):
        if t and not t.done(): t.cancel()
    if self._ws and self._ws.close_code is None: await self._ws.close()
    for t in (self._start_task, self._send_task, self._recv_task):
        if t:
            with suppress(asyncio.CancelledError, Exception): await t
    self.fail_waiters(RuntimeError('client closed'))
    self._ws = None

@patch
def stop_channels(self: JupyAsyncKernelClient):
    if self._close_task and not self._close_task.done(): return
    self._close_task = asyncio.create_task(self.aclose())

# %% ../nbs/00_core.ipynb #1263d477
@patch
async def start_kernel(self:JupyAsyncKernelClient, kernel_name="python3", **kwargs):
    model = await self.api.kernels.create_kernel(name=kernel_name, **kwargs)
    self.kernel_id = model["id"]
    return model

# %% ../nbs/00_core.ipynb #bc577f39
@patch
async def shutdown_kernel(self: JupyAsyncKernelClient):
    "Delete the kernel, then close this client: with the kernel gone the connection has nothing left to serve"
    try:
        if self.kernel_id: return await self.api.kernels.delete_kernel(kid=self.kernel_id)
    finally: await self.aclose()
@patch
async def interrupt_kernel(self: JupyAsyncKernelClient):
    if self.kernel_id: return await self.api.kernels.interrupt(kid=self.kernel_id)
@patch
async def restart_kernel(self: JupyAsyncKernelClient):
    if self.kernel_id: return await self.api.kernels.restart(kid=self.kernel_id)


# %% ../nbs/00_core.ipynb #3a76e29a
@patch
async def model(self: JupyAsyncKernelClient):
    "What the gateway reports about this kernel (jupyter's `kernel model`): `execution_state`, `pid`, `path`, ..."
    return await self.api.kernels.get_kernel(kid=self.kernel_id)

@patch
async def is_alive(self: JupyAsyncKernelClient):
    if not self.kernel_id: return False
    try: return bool(await self.model())
    except Exception: return False

# %% ../nbs/00_core.ipynb #60942186
@patch
async def kernel_for(self: KernelApi, path):
    "The non-dead kernel model bound to notebook `path`, or None"
    ms = await self.api.kernels.list_kernels(path=str(path))
    return next((m for m in ms if m['execution_state'] != 'dead'), None)

# %% ../nbs/00_core.ipynb #0e8ce8d5
@patch
async def _ensure_started(self: JupyAsyncKernelClient):
    if not self._start_task: self.start_channels()
    if self._start_task: await self._start_task

@patch
def send(self: JupyAsyncKernelClient, msg, channel: str):
    "Serialize `msg` (binary framing when it carries buffers) and queue its frame for `_send_loop`; returns the msg_id."
    msg = dict(msg)
    msg["channel"] = channel
    bufs = msg.get("buffers")
    if bufs:
        msg["buffers"] = [bytes(b) for b in bufs]
        payload = serialize_binary_message(msg)
    else:
        msg.pop("buffers", None)
        payload = dumps(msg)
    self._send_q.put_nowait(payload)
    return msg["header"]["msg_id"]

# %% ../nbs/00_core.ipynb #7bf0ff55
@patch
async def _send_loop(self: JupyAsyncKernelClient):
    assert self._ws is not None
    while True:
        payload = self._unsent if self._unsent is not None else await self._send_q.get()
        if payload is None: return
        self._unsent = payload
        try: await self._ws.send(payload)
        except Exception as e:
            log.warning("websocket send failed: %s", e)
            return  # the payload stays in `_unsent`: a reconnected send loop retries it first
        self._unsent = None

@patch
async def _recv_loop(self: JupyAsyncKernelClient):
    assert self._ws is not None
    with suppress(websockets.ConnectionClosed):
        async for data in self._ws:
            if isinstance(data, str): msg = loads(data)
            elif isinstance(data, bytes): msg = deserialize_binary_message(data)
            else: continue
            r = self.route(msg)
            if inspect.isawaitable(r): await r
    if self.reconnect and not self._closing: self._start_task = asyncio.create_task(self._reconnect())

# %% ../nbs/00_core.ipynb #3cd67196
@patch
async def _start_ws(self: JupyAsyncKernelClient):
    if self._ws and self._ws.close_code is None: return
    for t in (self._send_task, self._recv_task):
        if t and not t.done(): t.cancel()  # a stale send loop must not steal payloads from the new one
    params = {"session_id": self.session_id}
    if self.token: params["token"] = self.token
    ws_url = _join_url(self.base_url, self._kpath(suffix="/channels"), ws=True, params=params)
    self._ws = await websockets.connect(ws_url, ssl=self._ws_ssl(ws_url), additional_headers=self._headers, ping_interval=30, max_size=self.max_size)
    self._send_task = asyncio.create_task(self._send_loop())
    self._recv_task = asyncio.create_task(self._recv_loop())

# %% ../nbs/00_core.ipynb #6606950e
@patch
def _exec_req(self: JupyAsyncKernelClient, name, content=None, channel="shell", metadata=None, subshell_id=None, parent=None, msg_id=None, buffers=None):
    "Build a signed message and queue its frame, fire-and-forget; returns the msg_id."
    msg = self.session.msg(name, content, metadata=metadata, parent=parent)
    if buffers: msg["buffers"] = buffers
    if subshell_id: msg["header"]["subshell_id"] = subshell_id
    if msg_id: msg["header"]["msg_id"] = msg_id
    return self.send(msg, channel)

def _gen_request(self, name):
    "Generated `*_request` senders, each returning an awaitable of its reply; other names raise, so typos fail instead of sending bogus messages. Assigned onto the class below (a module-level `__getattr__` would become a PEP 562 hook)."
    if name.startswith("_") or not name.endswith("_request"): raise AttributeError(name)
    def _f(channel="shell", timeout=None, **kwargs): return self.request(name, kwargs or None, channel, timeout=timeout)
    return _f

JupyAsyncKernelClient.__getattr__ = _gen_request

# %% ../nbs/00_core.ipynb #f5d47bbe
@patch
def start_channels(self: JupyAsyncKernelClient, shell=True, iopub=True, stdin=True, control=True):
    if not (shell or iopub or stdin or control): return
    if self._start_task and not self._start_task.done(): return
    self._start_task = asyncio.create_task(self._start_ws())
    return self

# %% ../nbs/00_core.ipynb #08793aa7
@patch(as_prop=True)
def channels_running(self: JupyAsyncKernelClient): return bool(self._ws and self._ws.close_code is None)

# %% ../nbs/00_core.ipynb #f3407997
@patch
async def wait_for_ready(self: JupyAsyncKernelClient, timeout=None):
    await self._ensure_started()
    await self.kernel_info_request(timeout=timeout)

# %% ../nbs/00_core.ipynb #7daa3f7a
@patch
def execute(self: JupyAsyncKernelClient, code, silent=False, store_history=True, user_expressions=None, allow_stdin=None, stop_on_error=True,
    msg_id=None, metadata=None, subshell_id=None, buffers=None):
    "Send an `execute_request`, fire-and-forget; returns its msg_id."
    user_expressions = {} if user_expressions is None else user_expressions
    allow_stdin = self.allow_stdin if allow_stdin is None else allow_stdin
    if not isinstance(code, str): raise ValueError(f"code {code!r} must be a string")
    validate_string_dict(user_expressions)
    return self._exec_req("execute_request", dict(code=code, silent=silent, store_history=store_history, user_expressions=user_expressions,
        allow_stdin=allow_stdin, stop_on_error=stop_on_error), metadata=metadata, subshell_id=subshell_id, msg_id=msg_id, buffers=buffers)

# %% ../nbs/00_core.ipynb #d75ce9da
@patch
def create_subshell(self: JupyAsyncKernelClient, subshell_id=None, timeout=None):
    return self.create_subshell_request(subshell_id=subshell_id, channel="control", timeout=timeout)

@patch
def list_subshell(self: JupyAsyncKernelClient, timeout=None): return self.list_subshell_request(channel="control", timeout=timeout)

@patch
def delete_subshell(self: JupyAsyncKernelClient, subshell_id: str, timeout=None):
    return self.delete_subshell_request(subshell_id=subshell_id, channel="control", timeout=timeout)

# %% ../nbs/00_core.ipynb #76577cec
@patch
def release(self: JupyAsyncKernelClient, msg_id: str, status: str = "ok", timeout=None):
    "Complete a held execute (kernmini's `hold` metadata); `status='error'` makes the hold's reply an error, engaging the kernel's stop-on-error tail abort"
    return self.release_request(msg_id=msg_id, status=status, channel="control", timeout=timeout)

# %% ../nbs/00_core.ipynb #52045159
@patch
def comm_info(self: JupyAsyncKernelClient, target_name=None, timeout=None):
    return self.comm_info_request(target_name=target_name, timeout=timeout)

@patch
def kernel_info(self: JupyAsyncKernelClient, timeout=None): return self.kernel_info_request(timeout=timeout)

# %% ../nbs/00_core.ipynb #97540d7e
@patch
async def _reconnect(self: JupyAsyncKernelClient):
    "Redial with the same session id, with backoff; on a dead kernel or an expired ceiling, fail every pending reply and in-flight run."
    deadline, delay = time.monotonic() + self.reconnect_ceiling, 0.1
    while not self._closing:
        try:
            await self._start_ws()
            log.info("websocket reconnected")
            return
        except Exception as e:
            exc = None
            try: await self.model()
            except APIError as he:
                if he.status_code: exc = DeadKernelError(f'kernel {self.kernel_id} is gone: {he.message}')
            except Exception: pass  # the server is unreachable too: keep trying until the ceiling
            if exc is None and time.monotonic() > deadline: exc = ConnectionError(f'gave up reconnecting after {self.reconnect_ceiling}s: {e}')
            if exc:
                self.fail_waiters(exc)
                raise exc
            await asyncio.sleep(delay)
            delay = min(delay*2, 5.0)

# %% ../nbs/00_core.ipynb #893a89e0
@patch
def shutdown(self: JupyAsyncKernelClient, restart=False, timeout=None):
    return self.shutdown_request(restart=restart, channel="control", timeout=timeout)

# %% ../nbs/00_core.ipynb #1239b481
@patch(cls_method=True)
async def connect(cls:JupyAsyncKernelClient, base_url, kernel=None, token=None, timeout=60, verify=True, **kw):
    "Construct + create a kernel (or attach to `kernel`) + open channels + wait ready; a created kernel is `owned`"
    self = cls(base_url, kernel_id=kernel, token=token, verify=verify)
    if kernel is None:
        await self.start_kernel(**kw)
        self.owned = True
    self.start_channels()
    await self.wait_for_ready(timeout=timeout)
    return self

@patch
async def __aenter__(self:JupyAsyncKernelClient): return self

@patch
async def __aexit__(self:JupyAsyncKernelClient, *exc):
    if self.owned:
        with suppress(Exception): await self.shutdown_kernel()
    else: await self.aclose()
