"""An async Jupyter kernel client over HTTP and websockets

Docs: https://AnswerDotAI.github.io/jupyasyncclient/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['log', 'OUTPUT_MSGS', 'COMM_MSGS', 'rg_spec', 'build_spec', 'KernelApi', 'JupyAsyncKernelClient', 'DeadKernelError',
           'Run']

# %% ../nbs/00_core.ipynb #a0271b3e
import asyncio, functools, json, logging, os, ssl, time, uuid, websockets
from fasttransport.core import AsyncTransport
from fastspec.oapi import OpenAPIClient, SpecParser
from fastspec.errors import APIError
from pathlib import Path
from contextlib import suppress
from queue import Empty
from urllib.parse import urlencode, urlsplit, urlunsplit
from jupywire.session import Session, validate_string_dict, dumps, loads, serialize_binary_message, deserialize_binary_message
from jupywire.ops import EvalOps
from fastcore.basics import patch, nested_idx
from fastcore.xtras import dict2obj
from fastcore.net import urlread
from fastcore.nbio import msg2out
from fastcore.meta import use_kwargs_dict

# %% ../nbs/00_core.ipynb #1c375452
log = logging.getLogger('jupyasyncclient')

# %% ../nbs/00_core.ipynb #23408417
def _join_url(base, path, ws=False, params=None):
    u = urlsplit(base)
    scheme = {"http": "ws", "https": "wss"}.get(u.scheme, u.scheme) if ws else u.scheme
    base_path = u.path.rstrip("/")
    full_path = f"{base_path}/{path.lstrip('/')}" if path else base_path
    query = urlencode({k: v for k, v in (params or {}).items() if v is not None})
    return urlunsplit((scheme, u.netloc, full_path, query, ""))

# %% ../nbs/00_core.ipynb #b5f06ba9
@functools.cache
def rg_spec():
    "The bundled rustygate spec, loaded once per process from its compact `rg_spec` module."
    from jupyasyncclient.rg_spec import spec
    return SpecParser.from_dict(spec)

def build_spec(nm='jupyasyncclient/rg_spec.py', url='http://localhost:8787'):
    "Regenerate the compact spec module `rg_spec.py` from a running rustygate's `/openapi.json`."
    SpecParser.from_openapi(dict2obj(json.loads(urlread(f'{url}/openapi.json')))).save(nm)

class KernelApi:
    "Shared HTTP plumbing for the Jupyter kernels API: one transport, and the spec-generated ops on `api`."
    def __init__(self, base_url, token=None, headers=None, timeout=30, http_client=None, verify=True):
        self.base_url,self.token,self._timeout,self.verify = base_url.rstrip('/'),token or '',timeout,verify
        self._headers = {**(headers or {})}
        if self.token and 'Authorization' not in self._headers: self._headers['Authorization'] = f'token {self.token}'
        self.transport = AsyncTransport(timeout=timeout, client=http_client, base_headers=self._headers, verify=verify)
        self.api = OpenAPIClient(rg_spec(), transport=self.transport, base_url=self.base_url)

    def _ws_ssl(self, url):
        "An unverified ssl context when `verify=False` and `url` is wss, else None for the library default."
        if self.verify or not url.startswith('wss'): return None
        ctx = ssl.create_default_context()
        ctx.check_hostname,ctx.verify_mode = False,ssl.CERT_NONE
        return ctx

    def _kpath(self, kernel_id='', suffix=''): return f"/api/kernels/{kernel_id}{suffix}" if kernel_id else '/api/kernels'

# %% ../nbs/00_core.ipynb #7efec2a1
class JupyAsyncKernelClient(EvalOps, KernelApi):
    "AsyncKernelClient-ish API over the kernels HTTP API plus its websocket channels."
    allow_stdin = True
    def __init__(self, base_url, kernel_id=None, token=None, session_id=None, username=None, headers=None, timeout=30, http_client=None,
        reconnect=True, reconnect_ceiling=300.0, verify=True, max_size=256*2**20):
        super().__init__(base_url, token=token, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.kernel_id = kernel_id
        self.owned = False    # True only when `connect` created the kernel; honored by `__aexit__`
        self.session_id = session_id or uuid.uuid4().hex
        self.session = Session(session=self.session_id, username=username or os.environ.get("USER") or "")
        self._ws,self._start_task,self._send_task,self._recv_task,self._close_task = [None]*5
        self.reconnect,self.reconnect_ceiling,self._unsent,self._closing = reconnect,reconnect_ceiling,None,False
        self.max_size = max_size
        self._send_q = asyncio.Queue()
        self._queues = {k: asyncio.Queue() for k in ("shell", "control", "jmsg")}
        self._reply_waiters = {k: {} for k in ("shell", "control")}
        self._stale_replies = {k: set() for k in ("shell", "control")}
        self._last_stdin_req = None

    def _kpath(self, kernel_id='', suffix=''): return super()._kpath(kernel_id or self.kernel_id, suffix)

# %% ../nbs/00_core.ipynb #8dccd345
@patch
async def aclose(self: JupyAsyncKernelClient):
    self._closing = True
    if self._send_task and not self._send_task.done():   # the None sentinel ends `_send_loop` once the queue has drained
        self._send_q.put_nowait(None)
        with suppress(Exception):
            async with asyncio.timeout(2): await self._send_task
    for t in (self._start_task, self._send_task, self._recv_task):
        if t and not t.done(): t.cancel()
    if self._ws and self._ws.close_code is None: await self._ws.close()
    for t in (self._start_task, self._send_task, self._recv_task):
        if t:
            with suppress(asyncio.CancelledError, Exception): await t
    for d in self._reply_waiters.values():
        for fut, _ in d.values():
            if not fut.done(): fut.cancel()
        d.clear()
    for s in self._stale_replies.values(): s.clear()
    self._ws = None

@patch
def stop_channels(self: JupyAsyncKernelClient):
    if self._close_task and not self._close_task.done(): return
    self._close_task = asyncio.create_task(self.aclose())

# %% ../nbs/00_core.ipynb #1263d477
@patch
async def start_kernel(self:JupyAsyncKernelClient, kernel_name="python3", **kwargs):
    model = await self.api.kernels.create_kernel(name=kernel_name, **kwargs)
    self.kernel_id = model["id"]
    return model

# %% ../nbs/00_core.ipynb #bc577f39
@patch
async def shutdown_kernel(self: JupyAsyncKernelClient):
    "Delete the kernel, then close this client: with the kernel gone the connection has nothing left to serve"
    try:
        if self.kernel_id: return await self.api.kernels.delete_kernel(kid=self.kernel_id)
    finally: await self.aclose()
@patch
async def interrupt_kernel(self: JupyAsyncKernelClient):
    if self.kernel_id: return await self.api.kernels.interrupt(kid=self.kernel_id)
@patch
async def restart_kernel(self: JupyAsyncKernelClient):
    if self.kernel_id: return await self.api.kernels.restart(kid=self.kernel_id)

@patch
async def model(self: JupyAsyncKernelClient):
    "What the gateway reports about this kernel (jupyter's `kernel model`): `execution_state`, `pid`, `path`, ..."
    return await self.api.kernels.get_kernel(kid=self.kernel_id)

@patch
async def is_alive(self: JupyAsyncKernelClient):
    if not self.kernel_id: return False
    try: return bool(await self.model())
    except Exception: return False


# %% ../nbs/00_core.ipynb #60942186
@patch
async def kernel_for(self: KernelApi, path):
    "The non-dead kernel model bound to notebook `path`, or None"
    ms = await self.api.kernels.list_kernels(path=str(path))
    return next((m for m in ms if m['execution_state'] != 'dead'), None)

# %% ../nbs/00_core.ipynb #38c3312b
@patch
def _fail_pending(self: JupyAsyncKernelClient, exc, channel="shell", skip=None):
    "Fail all pending reply waiters on `channel` (except `skip`), e.g. when an error aborts the kernel's queue."
    for mid, (fut, _) in list(self._reply_waiters[channel].items()):
        if mid != skip and not fut.done(): fut.set_exception(exc)

@patch
def _route_reply_or_queue(self: JupyAsyncKernelClient, msg):
    channel = msg.get("channel") or "shell"
    msg.setdefault("msg_id", msg.get("header", {}).get("msg_id"))
    msg.setdefault("msg_type", msg.get("header", {}).get("msg_type"))
    msg.setdefault("buffers", [])
    if channel == "stdin" and msg["msg_type"] == "input_request": self._last_stdin_req = msg.get("header")
    parent_msg_id = msg.get("parent_header", {}).get("msg_id")
    if channel in self._reply_waiters and parent_msg_id:
        pend = self._reply_waiters[channel].pop(parent_msg_id, None)
        if pend:
            fut, fail_pending = pend
            if not fut.done(): fut.set_result(msg)
            cts = msg.get("content", {})
            if fail_pending and cts.get("status") in ("error", "aborted"):
                exc = RuntimeError(f"Kernel error aborted: {cts.get('ename')}: {cts.get('evalue')}")
                self._fail_pending(exc, channel, skip=parent_msg_id)
            return
        if parent_msg_id in self._stale_replies[channel]:
            self._stale_replies[channel].discard(parent_msg_id)
            return
    q = self._queues.get("jmsg" if channel in ("iopub", "stdin", "cells") else channel)
    if q: q.put_nowait(msg)

# %% ../nbs/00_core.ipynb #0e8ce8d5
@patch
async def _ensure_started(self: JupyAsyncKernelClient):
    if not self._start_task: self.start_channels()
    if self._start_task: await self._start_task

@patch
def _queue_msg(self: JupyAsyncKernelClient, msg, channel: str):
    msg = dict(msg)
    msg["channel"] = channel
    bufs = msg.get("buffers")
    if bufs:
        msg["buffers"] = [bytes(b) for b in bufs]
        payload = serialize_binary_message(msg)
    else:
        msg.pop("buffers", None)
        payload = dumps(msg)
    self._send_q.put_nowait(payload)
    return msg["header"]["msg_id"]

@patch
async def _get_msg(self: JupyAsyncKernelClient, channel, timeout=None):
    await self._ensure_started()
    q = self._queues[channel]
    try:
        async with asyncio.timeout(timeout): return await q.get()
    except asyncio.TimeoutError as e: raise Empty from e

# %% ../nbs/00_core.ipynb #7bf0ff55
@patch
async def _send_loop(self: JupyAsyncKernelClient):
    assert self._ws is not None
    while True:
        payload = self._unsent if self._unsent is not None else await self._send_q.get()
        if payload is None: return
        self._unsent = payload
        try: await self._ws.send(payload)
        except Exception as e:
            log.warning("websocket send failed: %s", e)
            return  # the payload stays in `_unsent`: a reconnected send loop retries it first
        self._unsent = None

@patch
async def _recv_loop(self: JupyAsyncKernelClient):
    assert self._ws is not None
    with suppress(websockets.ConnectionClosed):
        async for data in self._ws:
            if isinstance(data, str): msg = loads(data)
            elif isinstance(data, bytes): msg = deserialize_binary_message(data)
            else: continue
            self._route_reply_or_queue(msg)
    if self.reconnect and not self._closing: self._start_task = asyncio.create_task(self._reconnect())

# %% ../nbs/00_core.ipynb #3cd67196
@patch
async def _start_ws(self: JupyAsyncKernelClient):
    if self._ws and self._ws.close_code is None: return
    for t in (self._send_task, self._recv_task):
        if t and not t.done(): t.cancel()  # a stale send loop must not steal payloads from the new one
    params = {"session_id": self.session_id}
    if self.token: params["token"] = self.token
    ws_url = _join_url(self.base_url, self._kpath(suffix="/channels"), ws=True, params=params)
    self._ws = await websockets.connect(ws_url, ssl=self._ws_ssl(ws_url), additional_headers=self._headers, ping_interval=30, max_size=self.max_size)
    self._send_task = asyncio.create_task(self._send_loop())
    self._recv_task = asyncio.create_task(self._recv_loop())

# %% ../nbs/00_core.ipynb #0c4eb750
@patch
async def _await_reply(self: JupyAsyncKernelClient, fut, msg_id, timeout=None, channel="shell"):
    "Await a reply future registered by `_exec_req`; a timeout or cancellation marks the reply stale, so its late arrival is dropped"
    try:
        async with asyncio.timeout(timeout): return await fut
    finally:
        popped = self._reply_waiters[channel].pop(msg_id, None)
        if popped and popped[0] is fut and (not fut.done() or fut.cancelled()): self._stale_replies[channel].add(msg_id)

# %% ../nbs/00_core.ipynb #6606950e
@patch
def _exec_req(self: JupyAsyncKernelClient, name, content=None, channel="shell", metadata=None, reply=False, timeout=None, subshell_id=None,
    parent=None, fail_pending=False, msg_id=None):
    msg = self.session.msg(name, content, metadata=metadata, parent=parent)
    if subshell_id: msg["header"]["subshell_id"] = subshell_id
    if msg_id: msg["header"]["msg_id"] = msg_id
    else: msg_id = msg["header"]["msg_id"]
    if not reply: return self._queue_msg(msg, channel)
    fut = asyncio.get_running_loop().create_future()
    self._reply_waiters[channel][msg_id] = (fut, fail_pending)
    self._queue_msg(msg, channel)
    return self._await_reply(fut, msg_id, timeout=timeout, channel=channel)

def _gen_request(self, name):
    "Generated `*_request`/`*_reply` senders; other names raise, so typos fail instead of sending bogus messages. Assigned onto the class below (a module-level `__getattr__` would become a PEP 562 hook)."
    if name.startswith("_") or not name.endswith(("_request", "_reply")): raise AttributeError(name)
    def _f(reply=False, timeout=None, channel="shell", metadata=None, subshell_id=None, parent=None, fail_pending=False, msg_id=None, **kwargs):
        return self._exec_req(name, content=kwargs or None, reply=reply, timeout=timeout, channel=channel, metadata=metadata,
            subshell_id=subshell_id, parent=parent, fail_pending=fail_pending, msg_id=msg_id)
    return _f

JupyAsyncKernelClient.__getattr__ = _gen_request

# %% ../nbs/00_core.ipynb #f5d47bbe
@patch
def start_channels(self: JupyAsyncKernelClient, shell=True, iopub=True, stdin=True, control=True):
    if not (shell or iopub or stdin or control): return
    if self._start_task and not self._start_task.done(): return
    self._start_task = asyncio.create_task(self._start_ws())
    return self

# %% ../nbs/00_core.ipynb #08793aa7
@patch(as_prop=True)
def channels_running(self: JupyAsyncKernelClient): return bool(self._ws and self._ws.close_code is None)

# %% ../nbs/00_core.ipynb #22d28a55
@patch
async def get_shell_msg(self: JupyAsyncKernelClient, timeout=None): return await self._get_msg("shell", timeout)
@patch
async def get_jmsg(self: JupyAsyncKernelClient, timeout=None):
    "Next message from the merged iopub/stdin/cells stream; each dict says which in `channel`"
    return await self._get_msg("jmsg", timeout)
@patch
async def get_control_msg(self: JupyAsyncKernelClient, timeout=None): return await self._get_msg("control", timeout)

@patch
async def jmsg_for(self: JupyAsyncKernelClient, *msg_types, pred=None, timeout=None):
    "Next merged-stream message whose `msg_type` is in `msg_types` (and satisfies `pred`, if given), discarding the messages before it"
    try:
        async with asyncio.timeout(timeout):
            while True:
                m = await self.get_jmsg()
                if m['msg_type'] in msg_types and (pred is None or pred(m)): return m
    except TimeoutError as e: raise Empty from e

# %% ../nbs/00_core.ipynb #45e8b6c3
@patch
async def jmsg_flush(self:JupyAsyncKernelClient, timeout=0.2):
    "Discard queued merged-stream messages until none arrives for `timeout` seconds"
    while True:
        try: await self.get_jmsg(timeout=timeout)
        except Empty: return

# %% ../nbs/00_core.ipynb #f3407997
@patch
async def wait_for_ready(self: JupyAsyncKernelClient, timeout=None):
    await self._ensure_started()
    await self.kernel_info_request(reply=True, timeout=timeout)

# %% ../nbs/00_core.ipynb #65a13919
_replkw = dict(reply=False, timeout=None)
_subskw = dict(**_replkw, subshell_id=None)

# %% ../nbs/00_core.ipynb #7daa3f7a
@patch
@use_kwargs_dict(**_subskw)
def execute(self: JupyAsyncKernelClient, code, silent=False, store_history=True, user_expressions=None, allow_stdin=None, stop_on_error=True,
    fail_pending=False, msg_id=None, **kwargs):
    user_expressions = {} if user_expressions is None else user_expressions
    allow_stdin = self.allow_stdin if allow_stdin is None else allow_stdin
    if not isinstance(code, str): raise ValueError(f"code {code!r} must be a string")
    validate_string_dict(user_expressions)
    return self.execute_request(code=code, silent=silent, store_history=store_history, user_expressions=user_expressions,
        allow_stdin=allow_stdin, stop_on_error=stop_on_error, fail_pending=fail_pending, msg_id=msg_id, **kwargs)

# %% ../nbs/00_core.ipynb #d75ce9da
@patch
@use_kwargs_dict(**_replkw)
def create_subshell(self: JupyAsyncKernelClient, **kwargs): return self.create_subshell_request(channel="control", **kwargs)

@patch
@use_kwargs_dict(**_replkw)
def list_subshell(self: JupyAsyncKernelClient, **kwargs): return self.list_subshell_request(channel="control", **kwargs)

@patch
@use_kwargs_dict(**_replkw)
def delete_subshell_request(self: JupyAsyncKernelClient, subshell_id: str, metadata=None, **kwargs):
    return self._exec_req("delete_subshell_request", content={"subshell_id": subshell_id}, channel="control", metadata=metadata, **kwargs)

@patch
@use_kwargs_dict(**_replkw)
def delete_subshell(self: JupyAsyncKernelClient, subshell_id: str, **kwargs): return self.delete_subshell_request(subshell_id=subshell_id, **kwargs)

# %% ../nbs/00_core.ipynb #76577cec
@patch
@use_kwargs_dict(**_replkw)
def release(self: JupyAsyncKernelClient, msg_id: str, status: str = "ok", metadata=None, **kwargs):
    "Complete a held execute (kernmini's `hold` metadata); `status='error'` makes the hold's reply an error, engaging the kernel's stop-on-error tail abort"
    return self._exec_req("release_request", content={"msg_id": msg_id, "status": status}, channel="control", metadata=metadata, **kwargs)

# %% ../nbs/00_core.ipynb #057d4d1a
@patch
def input(self: JupyAsyncKernelClient, string: str):
    "Answer an `input_request`, parented to it so kernels and gateways can match reply to prompt."
    parent, self._last_stdin_req = self._last_stdin_req, None
    self.input_reply(value=string, channel="stdin", parent=parent)

# %% ../nbs/00_core.ipynb #b961668b
@patch
async def complete(self:JupyAsyncKernelClient, code, cursor_pos=None, timeout=15):
    "Completion `(matches, replace_start)` for `code` at `cursor_pos` (end when None)"
    cursor_pos = len(code) if cursor_pos is None else cursor_pos
    c = (await self.complete_request(code=code, cursor_pos=cursor_pos, reply=True, timeout=timeout))['content']
    return c.get('matches', []), c.get('cursor_start', cursor_pos)


# %% ../nbs/00_core.ipynb #2899c6b1
@patch
async def inspect(self:JupyAsyncKernelClient, code, cursor_pos=None, detail_level=0, timeout=15):
    "Inspection text for `code` at `cursor_pos` ('' when nothing found)"
    cursor_pos = len(code) if cursor_pos is None else cursor_pos
    c = (await self.inspect_request(code=code, cursor_pos=cursor_pos, detail_level=detail_level, reply=True, timeout=timeout))['content']
    return c.get('data', {}).get('text/plain', '') if c.get('found') else ''

@patch
async def check(self:JupyAsyncKernelClient, code, timeout=15):
    "('complete'|'incomplete'|'invalid'|'unknown', indent) for `code` as a cell"
    c = (await self.is_complete_request(code=code, reply=True, timeout=timeout))['content']
    return c.get('status', 'unknown'), c.get('indent', '')


# %% ../nbs/00_core.ipynb #9775d16f
@patch
@use_kwargs_dict(**_subskw, keep=True)
def history(self: JupyAsyncKernelClient, raw=True, output=False, hist_access_type="range", **kwargs):
    if hist_access_type=="range":
        kwargs.setdefault("session", 0)
        kwargs.setdefault("start", 0)
    return self.history_request(raw=raw, output=output, hist_access_type=hist_access_type, **kwargs)

# %% ../nbs/00_core.ipynb #52045159
@patch
@use_kwargs_dict(**_subskw)
def comm_info(self: JupyAsyncKernelClient, target_name=None, **kwargs): return self.comm_info_request(target_name=target_name, **kwargs)

@patch
@use_kwargs_dict(**_subskw)
def kernel_info(self: JupyAsyncKernelClient, **kwargs): return self.kernel_info_request(**kwargs)

# %% ../nbs/00_core.ipynb #905ece60
@patch
def reply(self:JupyAsyncKernelClient, code, user_expressions=None, timeout=None, **kw):
    "Sugar for `execute(reply=True)`: run `code` and await its `execute_reply`"
    return self.execute(code, user_expressions=user_expressions, reply=True, timeout=timeout, **kw)


# %% ../nbs/00_core.ipynb #12f13fc0
OUTPUT_MSGS = ('stream', 'display_data', 'execute_result', 'error')
COMM_MSGS = ('comm_open', 'comm_msg', 'comm_close')

class DeadKernelError(RuntimeError): pass

class Run:
    "One execution's typed output stream: parent-filtered iopub until reply+idle; single-use."
    def __init__(self, kc, code, on_stdin=None, on_comm=None, **kw):
        self.kc,self.on_stdin,self.on_comm = kc,on_stdin,on_comm
        self.msg_id = kc.execute(code, allow_stdin=on_stdin is not None, **kw)
        self.reply,self.status,self.execution_count = None,None,None

    async def __aiter__(self):
        chans = dict(jmsg=self.kc.get_jmsg, shell=self.kc.get_shell_msg)
        pend = {ch: asyncio.ensure_future(f(timeout=None)) for ch,f in chans.items()}
        done = idle = False
        try:
            while not (done and idle):
                ready,_ = await asyncio.wait(pend.values(), return_when=asyncio.FIRST_COMPLETED, timeout=1)
                if not ready:
                    if not await self.kc.is_alive(): raise DeadKernelError('kernel died while executing')
                    continue
                for t in ready:
                    ch = next(k for k,v in pend.items() if v is t)
                    msg = t.result()
                    pend[ch] = asyncio.ensure_future(chans[ch](timeout=None))
                    mt,c = msg['msg_type'],msg['content']
                    mine = nested_idx(msg, 'parent_header', 'msg_id') == self.msg_id
                    if ch == 'shell':
                        if mt == 'execute_reply' and mine:
                            self.reply,self.status,self.execution_count = msg,c.get('status'),c.get('execution_count')
                            done = True
                    elif msg['channel'] == 'stdin':
                        if mt == 'input_request' and mine: self.kc.input(await self.on_stdin(c.get('prompt', ''), c.get('password', False)))
                    elif mt == 'status' and c.get('execution_state') == 'idle' and mine: idle = True
                    elif mt in OUTPUT_MSGS and mine: yield msg2out(msg)
                    elif mt in COMM_MSGS and self.on_comm is not None: self.on_comm(mt, c)
        finally:
            for t in pend.values(): t.cancel()

    async def collect(self):
        "Drain the run, returning all outputs as a list."
        return [o async for o in self]

    def __await__(self): return self.collect().__await__()

@patch
def run(self:JupyAsyncKernelClient, code, on_stdin=None, on_comm=None, **kw):
    "Execute `code`, returning a `Run` over this execution's nbformat-shaped outputs."
    return Run(self, code, on_stdin=on_stdin, on_comm=on_comm, **kw)

# %% ../nbs/00_core.ipynb #97540d7e
@patch
async def _reconnect(self: JupyAsyncKernelClient):
    "Redial with the same session id, with backoff; on a dead kernel or an expired ceiling, fail the pending futures."
    deadline, delay = time.monotonic() + self.reconnect_ceiling, 0.1
    while not self._closing:
        try:
            await self._start_ws()
            log.info("websocket reconnected")
            return
        except Exception as e:
            exc = None
            try: await self.model()
            except APIError as he:
                if he.status_code: exc = DeadKernelError(f'kernel {self.kernel_id} is gone: {he.message}')
            except Exception: pass  # the server is unreachable too: keep trying until the ceiling
            if exc is None and time.monotonic() > deadline: exc = ConnectionError(f'gave up reconnecting after {self.reconnect_ceiling}s: {e}')
            if exc:
                for c in ('shell','control'): self._fail_pending(exc, c)
                raise exc
            await asyncio.sleep(delay)
            delay = min(delay*2, 5.0)

# %% ../nbs/00_core.ipynb #893a89e0
@patch
@use_kwargs_dict(**_replkw)
def shutdown(self: JupyAsyncKernelClient, restart=False, **kwargs):
    return self.shutdown_request(restart=restart, channel="control", **kwargs)

# %% ../nbs/00_core.ipynb #1239b481
@patch(cls_method=True)
async def connect(cls:JupyAsyncKernelClient, base_url, kernel=None, token=None, timeout=60, verify=True, **kw):
    "Construct + create a kernel (or attach to `kernel`) + open channels + wait ready; a created kernel is `owned`"
    self = cls(base_url, kernel_id=kernel, token=token, verify=verify)
    if kernel is None:
        await self.start_kernel(**kw)
        self.owned = True
    self.start_channels()
    await self.wait_for_ready(timeout=timeout)
    return self

@patch
async def __aenter__(self:JupyAsyncKernelClient): return self

@patch
async def __aexit__(self:JupyAsyncKernelClient, *exc):
    if self.owned:
        with suppress(Exception): await self.shutdown_kernel()
    else: await self.aclose()
