"""Files and cells over the gateway's contents and cells APIs

[rustygate](https://github.com/AnswerDotAI/rustygate) serves two REST families beside the kernels API: a jupyter-inspired files API (`/api/contents`) and a cells API (`/api/cells`, per-cell operations on notebooks). This page builds their clients: `JupyAsyncFilesClient` addresses files and directories by path, `JupyAsyncCellsClient` binds to one notebook's cells, and `apply_ops` is the reference applier for the `cell_ops` change broadcasts that arrive on a kernel client's merged stream (`get_jmsg`, `channel` `'cells'`).

Docs: https://AnswerDotAI.github.io/jupyasyncclient/files.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_files.ipynb.

# %% auto #0
__all__ = ['HashMismatch', 'JupyAsyncFilesClient', 'JupyAsyncCellsClient', 'apply_ops']

# %% ../nbs/02_files.ipynb #edf8880c
import httpx2
from base64 import b64encode, b64decode
from fastcore.basics import patch, patch_to
from .core import KernelApi

# %% ../nbs/02_files.ipynb #89287e61
class HashMismatch(Exception):
    "A conditional write failed; `hash` is the server's current file hash."
    def __init__(self, hash):
        super().__init__(f'expected_hash is stale; the current hash is {hash}')
        self.hash = hash

class JupyAsyncFilesClient(KernelApi):
    "Files and directories over the gateway's contents API."
    def __init__(self, base_url, token=None, session_id=None, headers=None, timeout=30, http_client=None, verify=True):
        super().__init__(base_url, token=token, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.session_id = session_id

# %% ../nbs/02_files.ipynb #3e15be7b
@patch
async def _creq(self:JupyAsyncFilesClient, method, path, expected_hash=None, params=None, **kw):
    if not path.startswith('/'): path = f'/api/contents/{path}' if path else '/api/contents'
    p = dict(params or {}, session_id=self.session_id, expected_hash=expected_hash)
    try: return await self._request(method, path, params={k:v for k,v in p.items() if v is not None}, **kw)
    except httpx2.HTTPStatusError as e:
        if e.response.status_code==409: raise HashMismatch(e.response.json()['hash']) from e
        raise

@patch
async def get(self:JupyAsyncFilesClient, path='', **kwargs):
    "The model at `path`; `kwargs` become query parameters, e.g. `fields`."
    return await self._creq('GET', path, params=kwargs)

@patch
async def put(self:JupyAsyncFilesClient, path, expected_hash=None, **kwargs):
    "PUT with `kwargs` as the JSON body."
    return await self._creq('PUT', path, expected_hash=expected_hash, json=kwargs)

@patch
async def post(self:JupyAsyncFilesClient, path, expected_hash=None, **kwargs):
    "POST with `kwargs` as the JSON body."
    return await self._creq('POST', path, expected_hash=expected_hash, json=kwargs)

@patch_to(JupyAsyncFilesClient)
async def patch(self, path, /, expected_hash=None, **kwargs):
    "PATCH with `kwargs` as the JSON body; `path` is positional-only, freeing the name for the body."
    return await self._creq('PATCH', path, expected_hash=expected_hash, json=kwargs)


# %% ../nbs/02_files.ipynb #a85d5ed9
@patch
async def write(self:JupyAsyncFilesClient, path, content, expected_hash=None):
    "Write `content` (`str` as text, `bytes` as base64), returning the model with its new `hash`."
    c,f = (b64encode(content).decode(),'base64') if isinstance(content, bytes) else (content,'text')
    return await self.put(path, expected_hash=expected_hash, content=c, format=f)

@patch
async def read(self:JupyAsyncFilesClient, path):
    "A file's contents: `str` for text, `bytes` for binary."
    m = await self.get(path, fields='content')
    return b64decode(m['content']) if m['format']=='base64' else m['content']

@patch
async def listing(self:JupyAsyncFilesClient, path='', fields=None):
    "The entries of directory `path`; `fields='hash'` adds each file's hash."
    return (await self.get(path, fields=fields))['content']


# %% ../nbs/02_files.ipynb #c55f2f20
@patch
async def mkdir(self:JupyAsyncFilesClient, path):
    "Create directory `path`; parents are not created."
    return await self.put(path, type='directory')

@patch
async def rename(self:JupyAsyncFilesClient, path, to):
    "Rename `path` to `to`, returning the new model."
    return await self.patch(path, path=to)

@patch
async def copy(self:JupyAsyncFilesClient, src, to):
    "Copy `src` to `to`, returning the new model."
    return await self.post(to, copy_from=src)

@patch
async def delete(self:JupyAsyncFilesClient, path, expected_hash=None):
    "Delete a file or an empty directory."
    return await self._creq('DELETE', path, expected_hash=expected_hash)


# %% ../nbs/02_files.ipynb #58b30b6d
class JupyAsyncCellsClient(JupyAsyncFilesClient):
    "One notebook's cells over the gateway's cells API."
    def __init__(self, base_url, path, token=None, session_id=None, headers=None, timeout=30, http_client=None, verify=True):
        super().__init__(base_url, token=token, session_id=session_id, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.path,self.hash = path,None

    def __getitem__(self, ids): return self._lookup(ids)

# %% ../nbs/02_files.ipynb #f408a806
@patch
def _npath(self:JupyAsyncCellsClient): return f'/api/cells/{self.path}'

@patch
async def cells(self:JupyAsyncCellsClient, ids=None):
    "The notebook's cells in document order, optionally filtered to `ids`."
    if ids is not None and not isinstance(ids, str): ids = ','.join(ids)
    m = await self.get(self._npath(), ids=ids)
    self.hash = m['hash']
    return m['cells']

@patch
async def hashes(self:JupyAsyncCellsClient):
    "Per-cell `{'id','hash'}` rows: the cheap form for sync."
    m = await self.get(self._npath(), fields='hashes')
    self.hash = m['hash']
    return m['cells']

@patch
async def apply(self:JupyAsyncCellsClient, ops, conditional=False):
    "Apply `ops` atomically, returning ids of added cells; `conditional=True` sends the cursor as `expected_hash`."
    m = await self.post(self._npath(), expected_hash=self.hash if conditional else None, ops=ops)
    self.hash = m['hash']
    return m['added_ids']

@patch
async def _lookup(self:JupyAsyncCellsClient, ids):
    one = isinstance(ids, str)
    want = [ids] if one else list(ids)
    got = await self.cells(ids=want)
    if len(got)!=len(want): raise KeyError(', '.join(i for i in want if i not in {c['id'] for c in got}))
    return got[0] if one else got

# %% ../nbs/02_files.ipynb #c4eec70d
def apply_ops(cells, ops):
    "Apply a `cell_ops` list to `cells` in place, in order, returning it."
    for o in ops:
        ids = [c['id'] for c in cells]
        if o['op']=='add':
            at = ids.index(o['after'])+1 if o.get('after') else ids.index(o['before']) if o.get('before') else len(cells)
            cells.insert(at, o['cell'])
        elif o['op']=='update': cells[ids.index(o['id'])].update({k:v for k,v in o.items() if k not in ('op','id')})
        elif o['op']=='delete': del cells[ids.index(o['id'])]
        else: raise ValueError(f"unhandled op: {o['op']}")
    return cells
