"""Files and cells over the gateway's contents and cells APIs

[rustygate](https://github.com/AnswerDotAI/rustygate) serves two REST families beside the kernels API: a jupyter-inspired files API (`/api/contents`) and a cells API (`/api/cells`, per-cell operations on notebooks). This page builds their clients: `JupyAsyncFilesClient` addresses files and directories by path, `JupyAsyncCellsClient` binds to one notebook's cells, and `apply_ops` is the reference applier for the `cell_ops` change broadcasts that arrive on a kernel client's merged stream (`get_jmsg`, `channel` `'cells'`).

Docs: https://AnswerDotAI.github.io/jupyasyncclient/files.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_files.ipynb.

# %% auto #0
__all__ = ['HashMismatch', 'JupyAsyncFilesClient', 'JupyAsyncCellsClient', 'apply_ops']

# %% ../nbs/02_files.ipynb #edf8880c
import json
from base64 import b64encode, b64decode
from fastcore.basics import patch, patch_to
from fasttransport.errors import APIError
from .core import KernelApi

# %% ../nbs/02_files.ipynb #89287e61
class HashMismatch(Exception):
    "A conditional write failed; `hash` is the server's current file hash."
    def __init__(self, hash):
        super().__init__(f'expected_hash is stale; the current hash is {hash}')
        self.hash = hash

class JupyAsyncFilesClient(KernelApi):
    "Files and directories over the gateway's contents API."
    def __init__(self, base_url, token=None, session_id=None, headers=None, timeout=30, http_client=None, verify=True):
        super().__init__(base_url, token=token, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.session_id = session_id

# %% ../nbs/02_files.ipynb #3e15be7b
@patch
async def _op(self:JupyAsyncFilesClient, op, **kw):
    "Call spec op `op` with `session_id` attached and None values dropped; a conditional-write 409 raises `HashMismatch`."
    kw = {k:v for k,v in dict(kw, session_id=self.session_id).items() if v is not None}
    try: return await op(**kw)
    except APIError as e:
        if e.status_code==409 and isinstance(e.raw, dict) and 'hash' in e.raw: raise HashMismatch(e.raw['hash']) from e
        raise


# %% ../nbs/02_files.ipynb #5f99f9ef
@patch
async def get(self:JupyAsyncFilesClient, path='', **kwargs):
    "The model at `path`; `kwargs` become query parameters, e.g. `fields`."
    if not path: return await self._op(self.api.contents.get_root, **kwargs)
    return await self._op(self.api.contents.get_path, path=path, **kwargs)

@patch
async def put(self:JupyAsyncFilesClient, path, expected_hash=None, **kwargs):
    "PUT to the contents API; `kwargs` are its body and query fields."
    return await self._op(self.api.contents.put_path, path=path, expected_hash=expected_hash, **kwargs)

@patch
async def post(self:JupyAsyncFilesClient, path, expected_hash=None, **kwargs):
    "POST to the contents API; `kwargs` are its body and query fields."
    return await self._op(self.api.contents.post_path, path=path, expected_hash=expected_hash, **kwargs)

# %% ../nbs/02_files.ipynb #b42a6bd7
@patch_to(JupyAsyncFilesClient)
async def patch(self, path, /, expected_hash=None, **kwargs):
    "PATCH with `kwargs` as the JSON body; `path` is positional-only, freeing the name for the body."
    return await self._op(self.api.contents.patch_path, path=path, expected_hash=expected_hash, body_=kwargs)

@patch
async def delete(self:JupyAsyncFilesClient, path, expected_hash=None):
    "Delete a file or an empty directory."
    return await self._op(self.api.contents.delete_path, path=path, expected_hash=expected_hash)

# %% ../nbs/02_files.ipynb #a85d5ed9
@patch
async def write(self:JupyAsyncFilesClient, path, content, expected_hash=None, unique=False):
    "Write `content` (`str` as text, `bytes` as base64), returning the model with its new `hash`; `unique` lands at a free `name_n.ext`."
    c,f = (b64encode(content).decode(),'base64') if isinstance(content, bytes) else (content,'text')
    return await self.put(path, expected_hash=expected_hash, unique=unique or None, content=c, format=f)

@patch
async def read(self:JupyAsyncFilesClient, path):
    "A file's contents: `str` for text, `bytes` for binary."
    m = await self.get(path, fields='content')
    return b64decode(m['content']) if m['format']=='base64' else m['content']

@patch
async def listing(self:JupyAsyncFilesClient, path='', fields=None):
    "The entries of directory `path`; `fields='hash'` adds each file's hash."
    return (await self.get(path, fields=fields))['content']


# %% ../nbs/02_files.ipynb #c55f2f20
@patch
async def mkdir(self:JupyAsyncFilesClient, path, parents=False):
    "Create directory `path`; `parents` creates missing ancestors like `mkdir -p`."
    return await self.put(path, parents=parents or None, type='directory')

@patch
async def rename(self:JupyAsyncFilesClient, path, to):
    "Rename `path` to `to`, returning the new model."
    return await self.patch(path, path=to)

@patch
async def copy(self:JupyAsyncFilesClient, src, to, unique=False):
    "Copy `src` to `to`, returning the new model; `unique` lands at a free `name_n.ext`."
    return await self.post(to, unique=unique or None, copy_from=src)


# %% ../nbs/02_files.ipynb #09ace5bf
@patch
async def edit(self:JupyAsyncFilesClient, path, f, tries=3):
    "Read the JSON file at `path`, apply `f` to the parsed object, and write it back conditionally, retrying a lost race"
    for _ in range(tries):
        m = await self.get(path, fields='content,hash')
        o = json.loads(m['content'])
        f(o)
        try: return await self.put(path, expected_hash=m['hash'], content=json.dumps(o, sort_keys=True, indent=1), format='text')
        except HashMismatch: pass
    raise RuntimeError(f'edit kept losing races for {path}')

# %% ../nbs/02_files.ipynb #58b30b6d
class JupyAsyncCellsClient(JupyAsyncFilesClient):
    "One notebook's cells over the gateway's cells API."
    def __init__(self, base_url, path, token=None, session_id=None, headers=None, timeout=30, http_client=None, verify=True):
        super().__init__(base_url, token=token, session_id=session_id, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.path,self.hash,self.matched = str(path),None,None

    def __getitem__(self, ids): return self._lookup(ids)

# %% ../nbs/02_files.ipynb #f408a806
def _cs(v):
    "A comma-separated str from a str, an int, an iterable, or None"
    if v is None or isinstance(v, str): return v
    return ','.join(map(str, v)) if hasattr(v, '__iter__') else str(v)

@patch
async def cells(self:JupyAsyncCellsClient,
    ids=None, # Cell ids to keep: comma-separated str, or a list
    idx=None, # Cell positions to keep: comma-separated str, or a list of ints, 0-based, negative from the end; unions with `ids`
    q=None, # Keep only cells whose source matches this regex (multiline, smart-case)
    cell_type=None, # Keep only cells of this type: 'code', 'markdown', or 'raw'
    meta=None, # Keep only cells whose metadata contains this dict as a recursive subset; a None value means "key present"
    meta_not=None, # Drop cells whose metadata contains this dict as a recursive subset
    limit=None, # Keep at most this many cells after filtering
    context=None, # Also return this many neighbours either side of each kept cell; `self.matched` then names the true matches
    fields=None, # Comma-separated extras: 'hashes', 'meta', 'attachments'
):
    "The notebook's cells in document order, optionally selected and filtered (the gateway's cells GET stages)."
    m = await self._op(self.api.cells.get_cells, path=self.path, ids=_cs(ids), idx=_cs(idx), q=q, cell_type=cell_type,
        meta=None if meta is None else json.dumps(meta), meta_not=None if meta_not is None else json.dumps(meta_not),
        limit=limit, context=context, fields=fields)
    self.hash = m['hash']
    self.matched = m.get('matched')
    return m['cells']


# %% ../nbs/02_files.ipynb #a55ffe0f
@patch
async def hashes(self:JupyAsyncCellsClient):
    "Per-cell `{'id','hash'}` rows: the cheap form for sync."
    m = await self._op(self.api.cells.get_cells, path=self.path, fields='hashes')
    self.hash = m['hash']
    return m['cells']

@patch
async def apply(self:JupyAsyncCellsClient, ops):
    "Apply `ops` atomically, returning ids of added cells."
    m = await self._op(self.api.cells.post_cells, path=self.path, ops=ops)
    self.hash = m['hash']
    return m['added_ids']

@patch
async def _lookup(self:JupyAsyncCellsClient, ids):
    one = isinstance(ids, str)
    want = [ids] if one else list(ids)
    got = await self.cells(ids=want)
    if len(got)!=len(want): raise KeyError(', '.join(i for i in want if i not in {c['id'] for c in got}))
    return got[0] if one else got

# %% ../nbs/02_files.ipynb #c4eec70d
def apply_ops(cells, ops):
    "Apply a `cell_ops` list to `cells` in place, in order, bending as the server does; returns `cells`"
    for o in ops:
        ids = [c['id'] for c in cells]
        op = o['op']
        if op=='update' and o['id'] in ids: cells[ids.index(o['id'])].update({k:v for k,v in o.items() if k not in ('op','id')})
        elif op in ('add','update'):
            c = dict(o['cell']) if op=='add' else {k:v for k,v in o.items() if k!='op'}
            if c.get('id') in ids: cells[ids.index(c['id'])].update({k:v for k,v in c.items() if k!='id'})
            else:
                c.setdefault('cell_type', 'code')
                c.setdefault('metadata', {})
                if c['cell_type']=='code':
                    c.setdefault('outputs', [])
                    c.setdefault('execution_count', None)
                anchor = o.get('after') or o.get('before')
                at = ids.index(anchor) + bool(o.get('after')) if anchor in ids else len(cells)
                cells.insert(at, c)
        elif op=='delete':
            if o['id'] in ids: del cells[ids.index(o['id'])]
        else: raise ValueError(f"unhandled op: {op}")
    return cells
