spec = {'base_url': '',
 'ops': [{'group': 'help', 'name': 'index', 'path': '/', 'verb': 'GET', 'summary': 'This listing: every route with its summary.'},
         {'group': 'att',
          'name': 'get_att',
          'path': '/api/att/{path}',
          'verb': 'GET',
          'summary': "One attachment's raw bytes, `Content-Type` from its stored mime.",
          'route_params': ['path'],
          'query_params': ['cell', 'attid'],
          'required_params': ['attid', 'cell', 'path'],
          'param_types': {'path': 'str', 'cell': 'str', 'attid': 'str'},
          'param_docs': {'path': 'Notebook path relative to the served root', 'cell': 'The cell the attachment belongs to', 'attid': "The attachment id: what `attachment:attid` in the cell's source names"}},
         {'group': 'cells',
          'name': 'get_cells',
          'path': '/api/cells/{path}',
          'verb': 'GET',
          'summary': "Read an ipynb's cells and optional notebook metadata.",
          'route_params': ['path'],
          'query_params': ['fields', 'ids', 'section', 'ancestors', 'before', 'after', 'ref', 'idx', 'q', 'cell_type', 'meta', 'meta_not', 'limit', 'context'],
          'required_params': ['path'],
          'param_types': {'path': 'str', 'fields': 'str', 'ids': 'str', 'section': 'str', 'ancestors': 'str', 'before': 'str', 'after': 'str', 'ref': 'str', 'idx': 'str', 'q': 'str', 'cell_type': 'str', 'meta': 'str', 'meta_not': 'str', 'limit': 'int', 'context': 'int'},
          'param_defaults': {'cell_type': None},
          'param_docs': {'path': 'Notebook path relative to the served root',
                         'fields': 'Comma-separated cell fields, e.g. `id,source`. `*` includes all fields, attachments and `tokens` (approximate token counts); `meta` adds notebook metadata. Omitted: all cell fields except attachments and `tokens`.',
                         'ids': 'Comma-separated cell ids to keep, in document order',
                         'section': 'Select this cell and its heading section, through the next heading of the same or higher level (excluded). A non-heading selects itself.',
                         'ancestors': "Select this cell's enclosing headings, outermost first, excluding the cell itself",
                         'before': 'Select every cell before this one, excluding it',
                         'after': 'Select every cell after this one, excluding it',
                         'ref': 'Serve the committed notebook at this git rev instead',
                         'idx': 'Comma-separated cell positions to also keep: 0-based, negative counts from the end; out of range is 400',
                         'q': 'Keep only cells whose source matches this regex (multiline; smart-case, so uppercase in the pattern forces case-sensitivity)',
                         'cell_type': 'Keep only cells of this type',
                         'meta': 'Keep only cells whose metadata contains this JSON object as a recursive subset; a null value means "key present"',
                         'meta_not': 'Drop cells whose metadata contains this JSON object as a recursive subset; a null value means "key present"',
                         'limit': 'Keep at most this many cells after filtering',
                         'context': 'Also return this many neighbouring cells either side of each kept cell; the response then carries `matched`'}},
         {'group': 'cells',
          'name': 'post_cells',
          'path': '/api/cells/{path}',
          'verb': 'POST',
          'summary': 'Apply cell ops in order and return `{"added_ids"}`. Last accepted edit wins.',
          'route_params': ['path'],
          'body_params': ['ops'],
          'request_content_type': 'application/json',
          'required_params': ['ops', 'path'],
          'param_types': {'path': 'str', 'ops': 'list'},
          'param_docs': {'path': 'Notebook path relative to the served root', 'ops': 'The edits, applied in order; an error stops before the remaining ops'}},
         {'group': 'contents', 'name': 'get_root', 'path': '/api/contents', 'verb': 'GET', 'summary': 'The served root as a directory model.', 'query_params': ['fields'], 'param_types': {'fields': 'str'}, 'param_docs': {'fields': '`content` includes the file body'}},
         {'group': 'contents',
          'name': 'get_path',
          'path': '/api/contents/{path}',
          'verb': 'GET',
          'summary': 'A file or directory model; 404 when absent.',
          'route_params': ['path'],
          'query_params': ['fields'],
          'required_params': ['path'],
          'param_types': {'path': 'str', 'fields': 'str'},
          'param_docs': {'path': 'Path relative to the served root; `..` is rejected (400)', 'fields': '`content` includes the file body'}},
         {'group': 'contents',
          'name': 'post_path',
          'path': '/api/contents/{path}',
          'verb': 'POST',
          'summary': 'Copy a file to this path, returning its model (201 on create, 200 on overwrite). Missing destination parents are created.',
          'route_params': ['path'],
          'query_params': ['overwrite', 'unique'],
          'body_params': ['copy_from'],
          'request_content_type': 'application/json',
          'required_params': ['copy_from', 'path'],
          'param_types': {'path': 'str', 'overwrite': 'bool', 'unique': 'bool', 'copy_from': 'str'},
          'param_docs': {'path': 'Destination path relative to the served root; `..` is rejected (400)', 'overwrite': 'Whether an existing destination may be overwritten (default true); false returns 409 if it exists', 'unique': 'Write to the first free `name_n.ext` beside the target instead', 'copy_from': 'The source path to copy from'}},
         {'group': 'contents',
          'name': 'put_path',
          'path': '/api/contents/{path}',
          'verb': 'PUT',
          'summary': 'Write a file or create a directory, returning its stat model: 201 on create, 200 on overwrite.',
          'route_params': ['path'],
          'query_params': ['overwrite', 'unique', 'parents'],
          'body_params': ['content', 'format', 'type'],
          'request_content_type': 'application/json',
          'required_params': ['path'],
          'param_types': {'path': 'str', 'overwrite': 'bool', 'unique': 'bool', 'parents': 'bool', 'content': 'str', 'format': 'str', 'type': 'str'},
          'param_defaults': {'format': None},
          'param_docs': {'path': 'Path relative to the served root; `..` is rejected (400)',
                         'overwrite': 'Whether an existing destination may be overwritten (default true); false returns 409 if it exists',
                         'unique': 'Write to the first free `name_n.ext` beside the target instead',
                         'parents': 'Create missing parents of a directory',
                         'content': 'The file body; default empty',
                         'format': 'How `content` is encoded; default `text`',
                         'type': '`directory` creates one instead of writing a file'}},
         {'group': 'contents',
          'name': 'patch_path',
          'path': '/api/contents/{path}',
          'verb': 'PATCH',
          'summary': "Rename a file or directory to the body's `path`, returning the model at its new path.",
          'route_params': ['path'],
          'request_content_type': 'application/json',
          'required_params': ['path'],
          'param_types': {'path': 'str'},
          'param_docs': {'path': 'The new path'}},
         {'group': 'contents', 'name': 'delete_path', 'path': '/api/contents/{path}', 'verb': 'DELETE', 'summary': 'Delete a file or an empty directory (204).', 'route_params': ['path'], 'required_params': ['path'], 'param_types': {'path': 'str'}, 'param_docs': {'path': 'Path relative to the served root; `..` is rejected (400)'}},
         {'group': 'exec',
          'name': 'exec',
          'path': '/api/exec',
          'verb': 'POST',
          'summary': 'Run an allowlisted command chain to completion: `{"stdout", "stderr", "returncode"}`.',
          'body_params': ['cmds', 'args', 'cwd', 'timeout', 'username'],
          'request_content_type': 'application/json',
          'required_params': ['cmds'],
          'param_types': {'cmds': 'list', 'args': 'list', 'cwd': 'str', 'timeout': 'float', 'username': 'str'},
          'param_defaults': {'args': []},
          'param_docs': {'cmds': 'Bash strings, joined with ` && `: the chain stops at the first failure',
                         'args': 'Strings arriving as `$1`..., so user text never interpolates into the script',
                         'cwd': 'Working directory, relative to the served root',
                         'timeout': 'Seconds before the chain is killed; default 60, max 600',
                         'username': 'Run the chain as this user, via sudo'}},
         {'group': 'kernels', 'name': 'list_kernels', 'path': '/api/kernels', 'verb': 'GET', 'summary': 'List kernel models, whatever their state.', 'query_params': ['path'], 'param_types': {'path': 'str'}, 'param_docs': {'path': 'Keep only the entries bound to this notebook path'}},
         {'group': 'kernels',
          'name': 'create_kernel',
          'path': '/api/kernels',
          'verb': 'POST',
          'summary': 'Get or create a kernel, returning its model (200 when existing, 201 when new).',
          'body_params': ['name', 'path', 'argv', 'cwd', 'env', 'appendenv', 'username'],
          'request_content_type': 'application/json',
          'param_types': {'name': 'str', 'path': 'str', 'argv': 'list', 'cwd': 'str', 'env': 'dict', 'appendenv': 'dict', 'username': 'str'},
          'param_docs': {'name': '`luau` selects the bundled native kernel. Other names retain legacy argv/default behavior.',
                         'path': "The notebook path to bind: every client on the kernel's websocket hears its change broadcasts",
                         'argv': 'The kernel command; default ipymini',
                         'cwd': "Working directory; relative to the served root. Defaults to a bound notebook's parent.",
                         'env': "Environment, replacing the gateway's",
                         'appendenv': "Environment entries added to the gateway's",
                         'username': 'Run the kernel as this user, via sudo'}},
         {'group': 'kernels', 'name': 'get_kernel', 'path': '/api/kernels/{kid}', 'verb': 'GET', 'summary': "One kernel's model; 404 when unknown.", 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'kernels',
          'name': 'rename_kernel',
          'path': '/api/kernels/{kid}',
          'verb': 'PATCH',
          'summary': "Rename this kernel's bound notebook without changing its id or subscriptions.",
          'route_params': ['kid'],
          'body_params': ['path'],
          'request_content_type': 'application/json',
          'required_params': ['kid', 'path'],
          'param_types': {'kid': 'str', 'path': 'str'},
          'param_docs': {'kid': 'Kernel id', 'path': 'Destination notebook path relative to the served root'}},
         {'group': 'kernels', 'name': 'delete_kernel', 'path': '/api/kernels/{kid}', 'verb': 'DELETE', 'summary': 'Shut the kernel down and forget it (204); 404 when unknown.', 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'kernels',
          'name': 'get_kernel_cells',
          'path': '/api/kernels/{kid}/cells',
          'verb': 'GET',
          'summary': 'Read the current notebook bound to this kernel, using the same selection as the path cells API.',
          'route_params': ['kid'],
          'query_params': ['fields', 'ids', 'section', 'ancestors', 'before', 'after', 'ref', 'idx', 'q', 'cell_type', 'meta', 'meta_not', 'limit', 'context'],
          'required_params': ['kid'],
          'param_types': {'kid': 'str', 'fields': 'str', 'ids': 'str', 'section': 'str', 'ancestors': 'str', 'before': 'str', 'after': 'str', 'ref': 'str', 'idx': 'str', 'q': 'str', 'cell_type': 'str', 'meta': 'str', 'meta_not': 'str', 'limit': 'int', 'context': 'int'},
          'param_defaults': {'cell_type': None},
          'param_docs': {'kid': 'Kernel id',
                         'fields': 'Comma-separated cell fields, e.g. `id,source`. `*` includes all fields, attachments and `tokens` (approximate token counts); `meta` adds notebook metadata. Omitted: all cell fields except attachments and `tokens`.',
                         'ids': 'Comma-separated cell ids to keep, in document order',
                         'section': 'Select this cell and its heading section, through the next heading of the same or higher level (excluded). A non-heading selects itself.',
                         'ancestors': "Select this cell's enclosing headings, outermost first, excluding the cell itself",
                         'before': 'Select every cell before this one, excluding it',
                         'after': 'Select every cell after this one, excluding it',
                         'ref': 'Serve the committed notebook at this git rev instead',
                         'idx': 'Comma-separated cell positions to also keep: 0-based, negative counts from the end; out of range is 400',
                         'q': 'Keep only cells whose source matches this regex (multiline; smart-case, so uppercase in the pattern forces case-sensitivity)',
                         'cell_type': 'Keep only cells of this type',
                         'meta': 'Keep only cells whose metadata contains this JSON object as a recursive subset; a null value means "key present"',
                         'meta_not': 'Drop cells whose metadata contains this JSON object as a recursive subset; a null value means "key present"',
                         'limit': 'Keep at most this many cells after filtering',
                         'context': 'Also return this many neighbouring cells either side of each kept cell; the response then carries `matched`'}},
         {'group': 'kernels',
          'name': 'post_kernel_cells',
          'path': '/api/kernels/{kid}/cells',
          'verb': 'POST',
          'summary': "Apply cell operations to the kernel's current notebook binding, including after a rename.",
          'route_params': ['kid'],
          'body_params': ['ops'],
          'request_content_type': 'application/json',
          'required_params': ['kid', 'ops'],
          'param_types': {'kid': 'str', 'ops': 'list'},
          'param_docs': {'kid': 'Kernel id', 'ops': 'The edits, applied in order; an error stops before the remaining ops'}},
         {'group': 'kernels',
          'name': 'channels_ws',
          'path': '/api/kernels/{kid}/channels',
          'verb': 'GET',
          'summary': "The kernel's client websocket: Jupyter messages with a `channel` key, as JSON or legacy binary frames.",
          'route_params': ['kid'],
          'query_params': ['session_id'],
          'required_params': ['kid'],
          'param_types': {'kid': 'str', 'session_id': 'str'},
          'param_docs': {'kid': 'Kernel id', 'session_id': 'Names the client for reply routing; generated when omitted'}},
         {'group': 'kernels', 'name': 'interrupt', 'path': '/api/kernels/{kid}/interrupt', 'verb': 'POST', 'summary': 'Send SIGINT to the kernel process (204); 404 when unknown.', 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'kernels',
          'name': 'kernel_realpath',
          'path': '/api/kernels/{kid}/realpath',
          'verb': 'GET',
          'summary': "The on-disk path relative to this kernel's notebook, or the served root with a leading slash.",
          'route_params': ['kid'],
          'query_params': ['path'],
          'required_params': ['kid'],
          'param_types': {'kid': 'str', 'path': 'str'},
          'param_defaults': {'path': ''},
          'param_docs': {'kid': 'Kernel id', 'path': "Relative to the notebook's parent; a leading slash selects the served root. Empty selects the parent."}},
         {'group': 'kernels', 'name': 'restart', 'path': '/api/kernels/{kid}/restart', 'verb': 'POST', 'summary': "Restart the kernel in place, keeping its id and its clients' websockets; returns the new model.", 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'search',
          'name': 'search',
          'path': '/api/search',
          'verb': 'GET',
          'summary': 'Find files under the served root by name, or by content with `q`: `{"paths", "complete"}`.',
          'query_params': ['q', 'up', 'fields', 'notebooks', 'case', 'path', 'dirs', 'glob', 'ext', 'path_re', 'skip_dir', 'depth', 'max_size', 'timeout_ms'],
          'param_types': {'q': 'str', 'up': 'str', 'fields': 'str', 'notebooks': 'bool', 'case': 'str', 'path': 'str', 'dirs': 'bool', 'glob': 'str', 'ext': 'str', 'path_re': 'str', 'skip_dir': 'str', 'depth': 'int', 'max_size': 'int', 'timeout_ms': 'int'},
          'param_defaults': {'notebooks': False, 'case': None, 'dirs': False},
          'param_docs': {'q': 'A regex over content; without it the search is a name walk',
                         'up': 'A bare name to find in `path` and each ancestor up to the root, nearest first: the ancestor walk, on which the other filters do not apply',
                         'fields': "Comma-separated extra fields for ancestor-walk hits: `content` adds each file's body",
                         'notebooks': 'Search ipynb cell sources only, over .ipynb files',
                         'case': 'Forces case sensitivity; the default is smart case, where the pattern decides',
                         'path': 'The directory to walk, relative to the served root; with `up`, it need not exist',
                         'dirs': 'Include directories in a name walk',
                         'glob': 'Comma-separated include globs, e.g. `*.py`',
                         'ext': 'Comma-separated extensions, e.g. `py,ipynb`',
                         'path_re': 'A regex relative paths must match',
                         'skip_dir': 'Comma-separated directory globs to prune',
                         'depth': 'Maximum walk depth',
                         'max_size': 'Skip files larger than this many bytes',
                         'timeout_ms': 'Bounds the walk in milliseconds; default 10000, max 60000'}},
         {'group': 'terminals', 'name': 'list_terms', 'path': '/api/terminals', 'verb': 'GET', 'summary': 'List terminal session models.', 'query_params': ['path'], 'param_types': {'path': 'str'}, 'param_docs': {'path': 'Keep only the entries bound to this notebook path'}},
         {'group': 'terminals',
          'name': 'create_term',
          'path': '/api/terminals',
          'verb': 'POST',
          'summary': 'Get or create a terminal session, returning its model (201).',
          'body_params': ['name', 'path', 'argv', 'username', 'env', 'appendenv', 'cwd', 'rows', 'cols', 'rc'],
          'request_content_type': 'application/json',
          'param_types': {'name': 'str', 'path': 'str', 'argv': 'list', 'username': 'str', 'env': 'dict', 'appendenv': 'dict', 'cwd': 'str', 'rows': 'int', 'cols': 'int', 'rc': 'str'},
          'param_docs': {'name': 'Session name; default the first free `t<n>`',
                         'path': 'Served-root-relative folder binding; an existing session bound to it is returned',
                         'argv': 'The command; default `$SHELL -i`',
                         'username': 'Run it as this user, via sudo',
                         'env': "Environment, replacing the gateway's",
                         'appendenv': "Environment entries added to the gateway's",
                         'cwd': 'Working directory, relative to the served root; defaults to the bound folder',
                         'rows': 'Initial rows; default 24',
                         'cols': 'Initial columns; default 80',
                         'rc': 'An rc-file body, written to a temp file; `{rcfile}` and `{rcdir}` substitute into argv and env'}},
         {'group': 'terminals', 'name': 'get_term', 'path': '/api/terminals/{name}', 'verb': 'GET', 'summary': "One session's model; 404 when unknown.", 'route_params': ['name'], 'required_params': ['name'], 'param_types': {'name': 'str'}, 'param_docs': {'name': 'Session name'}},
         {'group': 'terminals', 'name': 'delete_term', 'path': '/api/terminals/{name}', 'verb': 'DELETE', 'summary': "Kill the session's process and forget it (204); 404 when unknown.", 'route_params': ['name'], 'required_params': ['name'], 'param_types': {'name': 'str'}, 'param_docs': {'name': 'Session name'}},
         {'group': 'terminals', 'name': 'channel', 'path': '/api/terminals/{name}/channel', 'verb': 'GET', 'summary': "The session's websocket: pty bytes as binary frames, JSON control messages as text frames.", 'route_params': ['name'], 'required_params': ['name'], 'param_types': {'name': 'str'}, 'param_docs': {'name': 'Session name'}},
         {'group': 'help', 'name': 'index_2', 'path': '/help', 'verb': 'GET', 'summary': 'This listing: every route with its summary.'},
         {'group': 'help',
          'name': 'detail',
          'path': '/help/{path}',
          'verb': 'GET',
          'summary': "The routes at a path: each method's documented parameters and what it does.",
          'route_params': ['path'],
          'required_params': ['path'],
          'param_types': {'path': 'str'},
          'param_docs': {'path': 'A route path, as a template (`api/kernels/{kid}`) or a concrete instance (`api/kernels/abc`)'}},
         {'group': 'mcp', 'name': 'post', 'path': '/mcp', 'verb': 'POST'},
         {'group': 'mcp', 'name': 'delete_session', 'path': '/mcp', 'verb': 'DELETE'},
         {'group': 'mcp', 'name': 'post_scoped', 'path': '/mcp/{path}', 'verb': 'POST', 'route_params': ['path']},
         {'group': 'openapi_json', 'name': 'openapi_json', 'path': '/openapi.json', 'verb': 'GET', 'summary': 'This document: the whole API as OpenAPI 3.1, schemas included.'}]}
