spec = {'base_url': '',
 'ops': [{'group': 'help', 'name': 'index', 'path': '/', 'verb': 'GET', 'summary': 'This listing: every route with its summary.'},
         {'group': 'cells',
          'name': 'get_cells',
          'path': '/api/cells/{path}',
          'verb': 'GET',
          'summary': 'Parse an ipynb: `{"hash", "cells"}`, the hash over the file\'s bytes.',
          'route_params': ['path'],
          'query_params': ['fields', 'ids', 'ref'],
          'required_params': ['path'],
          'param_types': {'path': 'str', 'fields': 'str', 'ids': 'str', 'ref': 'str'},
          'param_docs': {'path': 'Notebook path relative to the served root', 'fields': 'Comma-separated costly extras: `hashes` replaces each cell with `{"id", "hash"}` for cheap sync, `meta` adds the notebook-level metadata', 'ids': 'Comma-separated cell ids to keep, in document order', 'ref': 'Serve the committed notebook at this git rev instead'}},
         {'group': 'cells',
          'name': 'post_cells',
          'path': '/api/cells/{path}',
          'verb': 'POST',
          'summary': 'Apply a batch of cell ops in order, atomically: `{"hash", "added_ids"}`.',
          'route_params': ['path'],
          'query_params': ['session_id', 'expected_hash'],
          'body_params': ['ops'],
          'request_content_type': 'application/json',
          'required_params': ['ops', 'path'],
          'param_types': {'path': 'str', 'session_id': 'str', 'expected_hash': 'str', 'ops': 'list'},
          'param_docs': {'path': 'Notebook path relative to the served root', 'session_id': 'Attributes the change, so its author is not re-notified', 'expected_hash': "Apply only if the file's current hash matches, else 409 with the current hash", 'ops': 'The edits, applied in order as one atomic batch'}},
         {'group': 'contents', 'name': 'get_root', 'path': '/api/contents', 'verb': 'GET', 'summary': 'The served root as a directory model.', 'query_params': ['fields'], 'param_types': {'fields': 'str'}, 'param_docs': {'fields': 'Comma-separated costly extras: `hash` (sha256 of the bytes), `content` (the body)'}},
         {'group': 'contents',
          'name': 'get_path',
          'path': '/api/contents/{path}',
          'verb': 'GET',
          'summary': 'A file or directory model; 404 when absent.',
          'route_params': ['path'],
          'query_params': ['fields'],
          'required_params': ['path'],
          'param_types': {'path': 'str', 'fields': 'str'},
          'param_docs': {'path': 'Path relative to the served root; `..` is rejected (400)', 'fields': 'Comma-separated costly extras: `hash` (sha256 of the bytes), `content` (the body)'}},
         {'group': 'contents',
          'name': 'post_path',
          'path': '/api/contents/{path}',
          'verb': 'POST',
          'summary': 'Copy a file to this path, returning its model (201 on create, 200 on overwrite).',
          'route_params': ['path'],
          'query_params': ['expected_hash', 'unique', 'session_id'],
          'body_params': ['copy_from'],
          'request_content_type': 'application/json',
          'required_params': ['copy_from', 'path'],
          'param_types': {'path': 'str', 'expected_hash': 'str', 'unique': 'bool', 'session_id': 'str', 'copy_from': 'str'},
          'param_docs': {'path': 'Destination path relative to the served root; `..` is rejected (400)',
                         'expected_hash': 'Makes the write conditional: 409 with the current hash when stale; empty means create-only',
                         'unique': 'Write to the first free `name_n.ext` beside the target instead',
                         'session_id': 'Attributes the change, so its author is not re-notified',
                         'copy_from': 'The source path to copy from'}},
         {'group': 'contents',
          'name': 'put_path',
          'path': '/api/contents/{path}',
          'verb': 'PUT',
          'summary': 'Write a file or create a directory, returning the model with the new `hash`: 201 on create, 200 on overwrite.',
          'route_params': ['path'],
          'query_params': ['expected_hash', 'unique', 'parents', 'session_id'],
          'body_params': ['content', 'format', 'type'],
          'request_content_type': 'application/json',
          'required_params': ['path'],
          'param_types': {'path': 'str', 'expected_hash': 'str', 'unique': 'bool', 'parents': 'bool', 'session_id': 'str', 'content': 'str', 'format': 'str', 'type': 'str'},
          'param_defaults': {'format': None},
          'param_docs': {'path': 'Path relative to the served root; `..` is rejected (400)',
                         'expected_hash': 'Makes the write conditional: 409 with the current hash when stale; empty means create-only',
                         'unique': 'Write to the first free `name_n.ext` beside the target instead',
                         'parents': 'Create missing parents of a directory',
                         'session_id': 'Attributes the change, so its author is not re-notified',
                         'content': 'The file body; default empty',
                         'format': 'How `content` is encoded; default `text`',
                         'type': '`directory` creates one instead of writing a file'}},
         {'group': 'contents',
          'name': 'patch_path',
          'path': '/api/contents/{path}',
          'verb': 'PATCH',
          'summary': "Rename a file or directory to the body's `path`, returning the model at its new path.",
          'route_params': ['path'],
          'query_params': ['expected_hash', 'session_id'],
          'request_content_type': 'application/json',
          'required_params': ['path'],
          'param_types': {'path': 'str', 'expected_hash': 'str', 'session_id': 'str'},
          'param_docs': {'path': 'The new path', 'expected_hash': 'Makes the change conditional: 409 with the current hash when stale', 'session_id': 'Attributes the change, so its author is not re-notified'}},
         {'group': 'contents',
          'name': 'delete_path',
          'path': '/api/contents/{path}',
          'verb': 'DELETE',
          'summary': 'Delete a file or an empty directory (204).',
          'route_params': ['path'],
          'query_params': ['expected_hash', 'session_id'],
          'required_params': ['path'],
          'param_types': {'path': 'str', 'expected_hash': 'str', 'session_id': 'str'},
          'param_docs': {'path': 'Path relative to the served root; `..` is rejected (400)', 'expected_hash': 'Makes the change conditional: 409 with the current hash when stale', 'session_id': 'Attributes the change, so its author is not re-notified'}},
         {'group': 'exec',
          'name': 'exec',
          'path': '/api/exec',
          'verb': 'POST',
          'summary': 'Run an allowlisted command chain to completion: `{"stdout", "stderr", "returncode"}`.',
          'body_params': ['cmds', 'args', 'cwd', 'timeout', 'username'],
          'request_content_type': 'application/json',
          'required_params': ['cmds'],
          'param_types': {'cmds': 'list', 'args': 'list', 'cwd': 'str', 'timeout': 'float', 'username': 'str'},
          'param_defaults': {'args': []},
          'param_docs': {'cmds': 'Bash strings, joined with ` && `: the chain stops at the first failure',
                         'args': 'Strings arriving as `$1`..., so user text never interpolates into the script',
                         'cwd': 'Working directory, relative to the served root',
                         'timeout': 'Seconds before the chain is killed; default 60, max 600',
                         'username': 'Run the chain as this user, via sudo'}},
         {'group': 'kernels', 'name': 'list_kernels', 'path': '/api/kernels', 'verb': 'GET', 'summary': 'List kernel models, whatever their state.', 'query_params': ['path'], 'param_types': {'path': 'str'}, 'param_docs': {'path': 'Keep only the entries bound to this notebook path'}},
         {'group': 'kernels',
          'name': 'create_kernel',
          'path': '/api/kernels',
          'verb': 'POST',
          'summary': 'Start a kernel and return its model (201).',
          'body_params': ['name', 'path', 'argv', 'cwd', 'env', 'appendenv', 'username'],
          'request_content_type': 'application/json',
          'param_types': {'name': 'str', 'path': 'str', 'argv': 'list', 'cwd': 'str', 'env': 'dict', 'appendenv': 'dict', 'username': 'str'},
          'param_docs': {'name': 'Kernelspec name: accepted for Jupyter API compatibility and ignored, since rustygate launches by argv',
                         'path': "The notebook path to bind: every client on the kernel's websocket hears its change broadcasts",
                         'argv': 'The kernel command; default ipymini',
                         'cwd': 'Its working directory',
                         'env': "Environment, replacing the gateway's",
                         'appendenv': "Environment entries added to the gateway's",
                         'username': 'Run the kernel as this user, via sudo'}},
         {'group': 'kernels', 'name': 'get_kernel', 'path': '/api/kernels/{kid}', 'verb': 'GET', 'summary': "One kernel's model; 404 when unknown.", 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'kernels', 'name': 'delete_kernel', 'path': '/api/kernels/{kid}', 'verb': 'DELETE', 'summary': 'Shut the kernel down and forget it (204); 404 when unknown.', 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'kernels',
          'name': 'channels_ws',
          'path': '/api/kernels/{kid}/channels',
          'verb': 'GET',
          'summary': "The kernel's client websocket: Jupyter messages with a `channel` key, as JSON or legacy binary frames.",
          'route_params': ['kid'],
          'query_params': ['session_id'],
          'required_params': ['kid'],
          'param_types': {'kid': 'str', 'session_id': 'str'},
          'param_docs': {'kid': 'Kernel id', 'session_id': 'Names the client and opts into buffered replay across reconnects; without it a disconnect discards the queue'}},
         {'group': 'kernels', 'name': 'interrupt', 'path': '/api/kernels/{kid}/interrupt', 'verb': 'POST', 'summary': 'Send SIGINT to the kernel process (204); 404 when unknown.', 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'kernels', 'name': 'restart', 'path': '/api/kernels/{kid}/restart', 'verb': 'POST', 'summary': "Restart the kernel in place, keeping its id and its clients' websockets; returns the new model.", 'route_params': ['kid'], 'required_params': ['kid'], 'param_types': {'kid': 'str'}, 'param_docs': {'kid': 'Kernel id'}},
         {'group': 'search',
          'name': 'search',
          'path': '/api/search',
          'verb': 'GET',
          'summary': 'Find files under the served root by name, or by content with `q`: `{"paths", "complete"}`.',
          'query_params': ['q', 'notebooks', 'case', 'path', 'dirs', 'glob', 'ext', 'path_re', 'skip_dir', 'depth', 'max_size', 'timeout_ms'],
          'param_types': {'q': 'str', 'notebooks': 'bool', 'case': 'str', 'path': 'str', 'dirs': 'bool', 'glob': 'str', 'ext': 'str', 'path_re': 'str', 'skip_dir': 'str', 'depth': 'int', 'max_size': 'int', 'timeout_ms': 'int'},
          'param_defaults': {'notebooks': False, 'case': None, 'dirs': False},
          'param_docs': {'q': 'A regex over content; without it the search is a name walk',
                         'notebooks': 'Search ipynb cell sources only, over .ipynb files',
                         'case': 'Forces case sensitivity; the default is smart case, where the pattern decides',
                         'path': 'The directory to walk, relative to the served root',
                         'dirs': 'Include directories in a name walk',
                         'glob': 'Comma-separated include globs, e.g. `*.py`',
                         'ext': 'Comma-separated extensions, e.g. `py,ipynb`',
                         'path_re': 'A regex relative paths must match',
                         'skip_dir': 'Comma-separated directory globs to prune',
                         'depth': 'Maximum walk depth',
                         'max_size': 'Skip files larger than this many bytes',
                         'timeout_ms': 'Bounds the walk in milliseconds; default 10000, max 60000'}},
         {'group': 'terminals', 'name': 'list_terms', 'path': '/api/terminals', 'verb': 'GET', 'summary': 'List terminal session models.', 'query_params': ['path'], 'param_types': {'path': 'str'}, 'param_docs': {'path': 'Keep only the entries bound to this notebook path'}},
         {'group': 'terminals',
          'name': 'create_term',
          'path': '/api/terminals',
          'verb': 'POST',
          'summary': 'Get or create a terminal session, returning its model (201).',
          'body_params': ['name', 'path', 'argv', 'username', 'env', 'appendenv', 'cwd', 'rows', 'cols', 'rc'],
          'request_content_type': 'application/json',
          'param_types': {'name': 'str', 'path': 'str', 'argv': 'list', 'username': 'str', 'env': 'dict', 'appendenv': 'dict', 'cwd': 'str', 'rows': 'int', 'cols': 'int', 'rc': 'str'},
          'param_docs': {'name': 'Session name; default the first free `t<n>`',
                         'path': 'A binding label: the session bound to it is returned instead of a new one',
                         'argv': 'The command; default `$SHELL -i`',
                         'username': 'Run it as this user, via sudo',
                         'env': "Environment, replacing the gateway's",
                         'appendenv': "Environment entries added to the gateway's",
                         'cwd': "Working directory, relative to the gateway's",
                         'rows': 'Initial rows; default 24',
                         'cols': 'Initial columns; default 80',
                         'rc': 'An rc-file body, written to a temp file; `{rcfile}` and `{rcdir}` substitute into argv and env'}},
         {'group': 'terminals', 'name': 'get_term', 'path': '/api/terminals/{name}', 'verb': 'GET', 'summary': "One session's model; 404 when unknown.", 'route_params': ['name'], 'required_params': ['name'], 'param_types': {'name': 'str'}, 'param_docs': {'name': 'Session name'}},
         {'group': 'terminals', 'name': 'delete_term', 'path': '/api/terminals/{name}', 'verb': 'DELETE', 'summary': "Kill the session's process and forget it (204); 404 when unknown.", 'route_params': ['name'], 'required_params': ['name'], 'param_types': {'name': 'str'}, 'param_docs': {'name': 'Session name'}},
         {'group': 'terminals', 'name': 'channel', 'path': '/api/terminals/{name}/channel', 'verb': 'GET', 'summary': "The session's websocket: pty bytes as binary frames, JSON control messages as text frames.", 'route_params': ['name'], 'required_params': ['name'], 'param_types': {'name': 'str'}, 'param_docs': {'name': 'Session name'}},
         {'group': 'help', 'name': 'index_2', 'path': '/help', 'verb': 'GET', 'summary': 'This listing: every route with its summary.'},
         {'group': 'help',
          'name': 'detail',
          'path': '/help/{path}',
          'verb': 'GET',
          'summary': "The routes at a path: each method's documented parameters and what it does.",
          'route_params': ['path'],
          'required_params': ['path'],
          'param_types': {'path': 'str'},
          'param_docs': {'path': 'A route path, as a template (`api/kernels/{kid}`) or a concrete instance (`api/kernels/abc`)'}},
         {'group': 'openapi_json', 'name': 'openapi_json', 'path': '/openapi.json', 'verb': 'GET', 'summary': 'This document: the whole API as OpenAPI 3.1, schemas included.'}]}
