"""A client for gateway-hosted terminals: REST lifecycle plus one websocket attachment

`JupyAsyncTerminalClient` connects to terminals hosted by [rustygate](https://github.com/AnswerDotAI/rustygate). An app can use it to provide a shell on the same machine and filesystem as its kernels, including inside a container. The gateway uses [ptymini](https://github.com/AnswerDotAI/ptymini) to manage the terminals.

The client uses `KernelApi` for terminal lifecycle requests at `/api/terminals` and a websocket for input, output and terminal controls.

## The channel

`connect` opens the websocket and returns the server's `setup` frame. The gateway then replays available scrollback as binary frames.

The websocket uses jupygate's protocol. Binary frames carry terminal bytes unchanged in either direction. Text frames contain JSON controls:

- The server sends `setup` when a client connects.
- `gap` reports that the client fell behind the server's replay buffer.
- `eof` reports the terminal's exit code.
- The client sends `set_size` to resize the terminal.

`write` sends bytes to the terminal. `resize` sends `set_size`. `frames` yields output as `bytes` and controls as dictionaries. Use one `frames` iterator per connection. Multiple iterators would compete to read the same socket.

`aclose` closes this client's websocket attachment. It does not delete the terminal. Use `shutdown_terminal` to stop the terminal for all clients.

Docs: https://AnswerDotAI.github.io/jupyasyncclient/term.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_term.ipynb.

# %% auto #0
__all__ = ['JupyAsyncTerminalClient']

# %% ../nbs/01_term.ipynb #0345edba
import json, websockets
from contextlib import suppress
from fastcore.basics import patch
from .core import KernelApi, _join_url

# %% ../nbs/01_term.ipynb #53b412c9
class JupyAsyncTerminalClient(KernelApi):
    "One gateway terminal: REST lifecycle through the spec ops on `api`, plus one ws attachment."
    def __init__(self, base_url, name=None, token=None, headers=None, timeout=30, http_client=None, verify=True):
        super().__init__(base_url, token=token, headers=headers, timeout=timeout, http_client=http_client, verify=verify)
        self.name,self._ws = name,None

    def _tpath(self, name=''): return f'/api/terminals/{name}' if name else '/api/terminals'
    async def list_terminals(self): return await self.api.terminals.list_terms()

    async def start_terminal(self, **kw):
        "Create a terminal (gateway creation options pass through) and bind its name."
        model = await self.api.terminals.create_term(**kw)
        self.name = model['name']
        return model

    async def shutdown_terminal(self): return await self.api.terminals.delete_term(name=self.name)

# %% ../nbs/01_term.ipynb #07b2b2a9
@patch
async def connect(self:JupyAsyncTerminalClient):
    "Open the terminal's ws channel and return the `setup` frame; replayed scrollback follows as binary."
    params = dict(token=self.token) if self.token else None
    url = _join_url(self.base_url, self._tpath(self.name)+'/channel', ws=True, params=params)
    self._ws = await websockets.connect(url, ssl=self._ws_ssl(url), max_size=None)
    return json.loads(await self._ws.recv())

@patch
async def write(self:JupyAsyncTerminalClient, data:bytes): await self._ws.send(data)

@patch
async def resize(self:JupyAsyncTerminalClient, rows:int, cols:int):
    await self._ws.send(json.dumps(dict(type='set_size', rows=rows, cols=cols)))

@patch
async def frames(self:JupyAsyncTerminalClient):
    "Incoming frames: pty output as `bytes`, control frames as parsed dicts. Ends when the ws closes."
    with suppress(websockets.ConnectionClosed):
        async for frame in self._ws: yield frame if isinstance(frame, bytes) else json.loads(frame)

@patch
async def aclose(self:JupyAsyncTerminalClient):
    if self._ws is not None:
        with suppress(Exception): await self._ws.close()
        self._ws = None
